package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TLogUserLogin;
import app.cn.qtt.bm.model.TLogUserLoginExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TLogUserLoginDAOImpl extends SqlMapClientDaoSupport implements TLogUserLoginDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TLogUserLoginDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer insert(TLogUserLogin record) {
    	Integer object =  (Integer) getSqlMapClientTemplate().insert("t_log_user_login.abatorgenerated_insert", record);
    	return object;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TLogUserLogin record) {
        int rows = getSqlMapClientTemplate().update("t_log_user_login.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TLogUserLogin record) {
        int rows = getSqlMapClientTemplate().update("t_log_user_login.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TLogUserLoginExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_log_user_login.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TLogUserLogin selectByPrimaryKey(Integer logUserLoginId) {
        TLogUserLogin key = new TLogUserLogin();
        key.setLogUserLoginId(logUserLoginId);
        TLogUserLogin record = (TLogUserLogin) getSqlMapClientTemplate().queryForObject("t_log_user_login.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TLogUserLoginExample example) {
        int rows = getSqlMapClientTemplate().delete("t_log_user_login.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer logUserLoginId) {
        TLogUserLogin key = new TLogUserLogin();
        key.setLogUserLoginId(logUserLoginId);
        int rows = getSqlMapClientTemplate().delete("t_log_user_login.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TLogUserLoginExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_log_user_login.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TLogUserLogin record, TLogUserLoginExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_log_user_login.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TLogUserLogin record, TLogUserLoginExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_log_user_login.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_log_user_login
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TLogUserLoginExample {
        private Object record;

        public UpdateByExampleParms(Object record, TLogUserLoginExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}