package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TLogUserAccess;
import app.cn.qtt.bm.model.TLogUserAccessExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TLogUserAccessDAOImpl extends SqlMapClientDaoSupport implements TLogUserAccessDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TLogUserAccessDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TLogUserAccess record) {
        getSqlMapClientTemplate().insert("t_log_user_access.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TLogUserAccess record) {
        int rows = getSqlMapClientTemplate().update("t_log_user_access.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TLogUserAccess record) {
        int rows = getSqlMapClientTemplate().update("t_log_user_access.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TLogUserAccessExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_log_user_access.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TLogUserAccess selectByPrimaryKey(Integer userLogId) {
        TLogUserAccess key = new TLogUserAccess();
        key.setUserLogId(userLogId);
        TLogUserAccess record = (TLogUserAccess) getSqlMapClientTemplate().queryForObject("t_log_user_access.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TLogUserAccessExample example) {
        int rows = getSqlMapClientTemplate().delete("t_log_user_access.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer userLogId) {
        TLogUserAccess key = new TLogUserAccess();
        key.setUserLogId(userLogId);
        int rows = getSqlMapClientTemplate().delete("t_log_user_access.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TLogUserAccessExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_log_user_access.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TLogUserAccess record, TLogUserAccessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_log_user_access.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TLogUserAccess record, TLogUserAccessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_log_user_access.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TLogUserAccessExample {
        private Object record;

        public UpdateByExampleParms(Object record, TLogUserAccessExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}