package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TOrderInfoGoods;
import app.cn.qtt.bm.model.TOrderInfoGoodsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TOrderInfoGoodsDAOImpl extends SqlMapClientDaoSupport implements TOrderInfoGoodsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TOrderInfoGoodsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TOrderInfoGoods record) {
        getSqlMapClientTemplate().insert("t_order_info_goods.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TOrderInfoGoods record) {
        int rows = getSqlMapClientTemplate().update("t_order_info_goods.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TOrderInfoGoods record) {
        int rows = getSqlMapClientTemplate().update("t_order_info_goods.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TOrderInfoGoodsExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_order_info_goods.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TOrderInfoGoods selectByPrimaryKey(Integer orderGoodsId) {
        TOrderInfoGoods key = new TOrderInfoGoods();
        key.setOrderGoodsId(orderGoodsId);
        TOrderInfoGoods record = (TOrderInfoGoods) getSqlMapClientTemplate().queryForObject("t_order_info_goods.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TOrderInfoGoodsExample example) {
        int rows = getSqlMapClientTemplate().delete("t_order_info_goods.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer orderGoodsId) {
        TOrderInfoGoods key = new TOrderInfoGoods();
        key.setOrderGoodsId(orderGoodsId);
        int rows = getSqlMapClientTemplate().delete("t_order_info_goods.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TOrderInfoGoodsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_order_info_goods.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TOrderInfoGoods record, TOrderInfoGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_order_info_goods.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TOrderInfoGoods record, TOrderInfoGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_order_info_goods.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TOrderInfoGoodsExample {
        private Object record;

        public UpdateByExampleParms(Object record, TOrderInfoGoodsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}