package app.cn.qtt.bm.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import app.cn.qtt.bm.model.TOrderInfoShop;
import app.cn.qtt.bm.model.TOrderInfoShopExample;

public class TOrderInfoShopDAOImpl extends SqlMapClientDaoSupport implements TOrderInfoShopDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public TOrderInfoShopDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void insert(TOrderInfoShop record) {
		getSqlMapClientTemplate().insert(
				"t_order_info_shop.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int updateByPrimaryKey(TOrderInfoShop record) {
		int rows = getSqlMapClientTemplate().update(
				"t_order_info_shop.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int updateByPrimaryKeySelective(TOrderInfoShop record) {
		int rows = getSqlMapClientTemplate()
				.update("t_order_info_shop.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public List selectByExample(TOrderInfoShopExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_order_info_shop.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public TOrderInfoShop selectByPrimaryKey(Integer orderShopId) {
		TOrderInfoShop key = new TOrderInfoShop();
		key.setOrderShopId(orderShopId);
		TOrderInfoShop record = (TOrderInfoShop) getSqlMapClientTemplate()
				.queryForObject(
						"t_order_info_shop.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int deleteByExample(TOrderInfoShopExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_order_info_shop.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int deleteByPrimaryKey(Integer orderShopId) {
		TOrderInfoShop key = new TOrderInfoShop();
		key.setOrderShopId(orderShopId);
		int rows = getSqlMapClientTemplate().delete(
				"t_order_info_shop.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int countByExample(TOrderInfoShopExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_order_info_shop.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int updateByExampleSelective(TOrderInfoShop record,
			TOrderInfoShopExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_order_info_shop.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public int updateByExample(TOrderInfoShop record,
			TOrderInfoShopExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_order_info_shop.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_order_info_shop
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private static class UpdateByExampleParms extends TOrderInfoShopExample {
		private Object record;

		public UpdateByExampleParms(Object record, TOrderInfoShopExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List calculatePriceAndAmount(TOrderInfoShop record) {
		return  (List) getSqlMapClientTemplate().queryForList(
				"t_order_info_shop.abatorgenerated_calculatePrice", record);
	}

	@Override
	public List selectShopOrderDetail(TOrderInfoShop record) {
		return (List) getSqlMapClientTemplate().queryForList("t_order_info_shop.selectShopOrderDetail", record);
	}

	/**
	 * @see app.cn.qtt.bm.dao.TOrderInfoShopDAO#selectByVerifyCondition(java.lang.String, java.lang.String)
	 * @param shortPhoneNumber
	 * @param captchas
	 * @return
	 * @author Gabriel
	 * @createtime 2013-9-17 上午11:05:58
	 */
	@Override
	public List selectByVerifyCondition(String shortPhoneNumber, String captchas) {
		Map<String, Object> paramMap = new HashMap<String, Object>();
		paramMap.put("shortPhoneNumber", shortPhoneNumber);
		paramMap.put("captchas", captchas);
		
		List list = getSqlMapClientTemplate().queryForList("t_order_info_shop.selectByVerifyCondition", paramMap);
		
		return list;
	}
	
}
