package app.cn.qtt.bm.dao;

import java.util.List;
import java.util.Map;

import app.cn.qtt.bm.model.MyOrder;
import app.cn.qtt.bm.model.OrderOperateBean;
import app.cn.qtt.bm.model.ShopOrderdailyStatistics;
import app.cn.qtt.bm.model.TOrderInfo;
import app.cn.qtt.bm.model.TOrderInfoExample;

public interface TOrderInfoDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    void insert(TOrderInfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKey(TOrderInfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKeySelective(TOrderInfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    List selectByExample(TOrderInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    TOrderInfo selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByExample(TOrderInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int countByExample(TOrderInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExampleSelective(TOrderInfo record, TOrderInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExample(TOrderInfo record, TOrderInfoExample example);
    
    /**
     * 查询商家每日统计信息
     * @param shopOrderdailyStatistics
     * @return List
     * @author GeYanmeng
     * @date 2013-6-18
     */
    List selectShopOrderDailyStatistics(ShopOrderdailyStatistics shopOrderdailyStatistics);
    
    /**
     * 查询我的饭盒
     * @param myOrder
     * @return
     * @author GeYanmeng
     * @date 2013-6-25
     */
    List selectMyOrderInfo(MyOrder myOrder);
    
    List selectMyOrderInfo2(MyOrder myOrder);
    
    List selectMyOrderByUserCodeAndTime(MyOrder myOrder);
    
    public List selectMyOrderInfo3(MyOrder myOrder);
    
    
    List<OrderOperateBean> selectOrderOperateDetail(Map<String,Object> params);
    
    public List<OrderOperateBean> selectInvalidUserOrderOperateDetail(Map<String,Object> params);
}