package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSendEmailHistory;
import app.cn.qtt.bm.model.TSendEmailHistoryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSendEmailHistoryDAOImpl extends SqlMapClientDaoSupport implements TSendEmailHistoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public TSendEmailHistoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public void insert(TSendEmailHistory record) {
        getSqlMapClientTemplate().insert("t_send_email_history.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int updateByPrimaryKey(TSendEmailHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_email_history.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int updateByPrimaryKeySelective(TSendEmailHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_email_history.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public List selectByExample(TSendEmailHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_send_email_history.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public TSendEmailHistory selectByPrimaryKey(Integer historyEmailId) {
        TSendEmailHistory key = new TSendEmailHistory();
        key.setHistoryEmailId(historyEmailId);
        TSendEmailHistory record = (TSendEmailHistory) getSqlMapClientTemplate().queryForObject("t_send_email_history.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int deleteByExample(TSendEmailHistoryExample example) {
        int rows = getSqlMapClientTemplate().delete("t_send_email_history.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int deleteByPrimaryKey(Integer historyEmailId) {
        TSendEmailHistory key = new TSendEmailHistory();
        key.setHistoryEmailId(historyEmailId);
        int rows = getSqlMapClientTemplate().delete("t_send_email_history.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int countByExample(TSendEmailHistoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_send_email_history.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int updateByExampleSelective(TSendEmailHistory record, TSendEmailHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_email_history.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public int updateByExample(TSendEmailHistory record, TSendEmailHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_email_history.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    private static class UpdateByExampleParms extends TSendEmailHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSendEmailHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}