package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSendMmsBuffer;
import app.cn.qtt.bm.model.TSendMmsBufferExample;

import java.sql.SQLException;
import java.util.List;

public interface TSendMmsBufferDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    void insert(TSendMmsBuffer record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKey(TSendMmsBuffer record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKeySelective(TSendMmsBuffer record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    List selectByExample(TSendMmsBufferExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    TSendMmsBuffer selectByPrimaryKey(Integer mmsId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByExample(TSendMmsBufferExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByPrimaryKey(Integer mmsId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int countByExample(TSendMmsBufferExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExampleSelective(TSendMmsBuffer record, TSendMmsBufferExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExample(TSendMmsBuffer record, TSendMmsBufferExample example);

	/**
	 * 批量插入彩信发送buffer表
	 * @param mmsBufferList
	 * @author GeYanmeng
	 * @throws SQLException 
	 * @date 2013-6-17
	 */
	void batchInsert(List<TSendMmsBuffer> mmsBufferList) throws SQLException;
}