package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSendEmailBuffer;
import app.cn.qtt.bm.model.TSendEmailBufferExample;

import java.sql.SQLException;
import java.util.List;

public interface TSendEmailBufferDAO {
    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	void insert(TSendEmailBuffer record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int updateByPrimaryKey(TSendEmailBuffer record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int updateByPrimaryKeySelective(TSendEmailBuffer record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	List selectByExample(TSendEmailBufferExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	TSendEmailBuffer selectByPrimaryKey(Integer bufferEmailId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int deleteByExample(TSendEmailBufferExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int deleteByPrimaryKey(Integer bufferEmailId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int countByExample(TSendEmailBufferExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int updateByExampleSelective(TSendEmailBuffer record,
			TSendEmailBufferExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_send_email_buffer
	 * @abatorgenerated  Fri Jun 21 11:12:52 CST 2013
	 */
	int updateByExample(TSendEmailBuffer record, TSendEmailBufferExample example);

	/**
	 * 批量插入邮件发送buffer表
	 * @param sendEmailBufferList
	 * @author GeYanmeng
	 * @throws SQLException 
	 * @date 2013-6-17
	 */
	void batchInsert(List<TSendEmailBuffer> sendEmailBufferList) throws SQLException;
}