package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSendSmsHistory;
import app.cn.qtt.bm.model.TSendSmsHistoryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSendSmsHistoryDAOImpl extends SqlMapClientDaoSupport implements TSendSmsHistoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSendSmsHistoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSendSmsHistory record) {
        getSqlMapClientTemplate().insert("t_send_sms_history.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TSendSmsHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_sms_history.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSendSmsHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_sms_history.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TSendSmsHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_send_sms_history.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSendSmsHistory selectByPrimaryKey(Long historyId) {
        TSendSmsHistory key = new TSendSmsHistory();
        key.setHistoryId(historyId);
        TSendSmsHistory record = (TSendSmsHistory) getSqlMapClientTemplate().queryForObject("t_send_sms_history.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSendSmsHistoryExample example) {
        int rows = getSqlMapClientTemplate().delete("t_send_sms_history.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Long historyId) {
        TSendSmsHistory key = new TSendSmsHistory();
        key.setHistoryId(historyId);
        int rows = getSqlMapClientTemplate().delete("t_send_sms_history.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSendSmsHistoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_send_sms_history.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSendSmsHistory record, TSendSmsHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_sms_history.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TSendSmsHistory record, TSendSmsHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_sms_history.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_send_sms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSendSmsHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSendSmsHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}