package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSendMmsHistory;
import app.cn.qtt.bm.model.TSendMmsHistoryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSendMmsHistoryDAOImpl extends SqlMapClientDaoSupport implements TSendMmsHistoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSendMmsHistoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSendMmsHistory record) {
        getSqlMapClientTemplate().insert("t_send_mms_history.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(TSendMmsHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_mms_history.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(TSendMmsHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_mms_history.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSendMmsHistory record) {
        int rows = getSqlMapClientTemplate().update("t_send_mms_history.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExampleWithoutBLOBs(TSendMmsHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_send_mms_history.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExampleWithBLOBs(TSendMmsHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_send_mms_history.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSendMmsHistory selectByPrimaryKey(Integer mmsHistoryId) {
        TSendMmsHistory key = new TSendMmsHistory();
        key.setMmsHistoryId(mmsHistoryId);
        TSendMmsHistory record = (TSendMmsHistory) getSqlMapClientTemplate().queryForObject("t_send_mms_history.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSendMmsHistoryExample example) {
        int rows = getSqlMapClientTemplate().delete("t_send_mms_history.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer mmsHistoryId) {
        TSendMmsHistory key = new TSendMmsHistory();
        key.setMmsHistoryId(mmsHistoryId);
        int rows = getSqlMapClientTemplate().delete("t_send_mms_history.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSendMmsHistoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_send_mms_history.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSendMmsHistory record, TSendMmsHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_mms_history.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleWithBLOBs(TSendMmsHistory record, TSendMmsHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_mms_history.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleWithoutBLOBs(TSendMmsHistory record, TSendMmsHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_mms_history.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_send_mms_history
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSendMmsHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSendMmsHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}