package app.cn.qtt.bm.dao;

import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import app.cn.qtt.bm.model.TSendMmsBuffer;
import app.cn.qtt.bm.model.TSendMmsBufferExample;

import com.ibatis.sqlmap.client.SqlMapClient;

public class TSendMmsBufferDAOImpl extends SqlMapClientDaoSupport implements TSendMmsBufferDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSendMmsBufferDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSendMmsBuffer record) {
        getSqlMapClientTemplate().insert("t_send_mms_buffer.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TSendMmsBuffer record) {
        int rows = getSqlMapClientTemplate().update("t_send_mms_buffer.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSendMmsBuffer record) {
        int rows = getSqlMapClientTemplate().update("t_send_mms_buffer.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TSendMmsBufferExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_send_mms_buffer.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSendMmsBuffer selectByPrimaryKey(Integer mmsId) {
        TSendMmsBuffer key = new TSendMmsBuffer();
        key.setMmsId(mmsId);
        TSendMmsBuffer record = (TSendMmsBuffer) getSqlMapClientTemplate().queryForObject("t_send_mms_buffer.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSendMmsBufferExample example) {
        int rows = getSqlMapClientTemplate().delete("t_send_mms_buffer.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer mmsId) {
        TSendMmsBuffer key = new TSendMmsBuffer();
        key.setMmsId(mmsId);
        int rows = getSqlMapClientTemplate().delete("t_send_mms_buffer.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSendMmsBufferExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_send_mms_buffer.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSendMmsBuffer record, TSendMmsBufferExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_mms_buffer.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TSendMmsBuffer record, TSendMmsBufferExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_send_mms_buffer.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_send_mms_buffer
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSendMmsBufferExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSendMmsBufferExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public void batchInsert(List<TSendMmsBuffer> mmsBufferList) throws SQLException {
		SqlMapClient sqlMapClient = getSqlMapClientTemplate().getSqlMapClient();
		sqlMapClient.startBatch();
		for(TSendMmsBuffer sendMmsBuffer:mmsBufferList){
			getSqlMapClientTemplate().insert("t_send_mms_buffer.abatorgenerated_insert", sendMmsBuffer);
		}
		sqlMapClient.executeBatch();
	}
}