package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TShopCategoryGoodsLink;
import app.cn.qtt.bm.model.TShopCategoryGoodsLinkExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TShopCategoryGoodsLinkDAOImpl extends SqlMapClientDaoSupport implements TShopCategoryGoodsLinkDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TShopCategoryGoodsLinkDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void insert(TShopCategoryGoodsLink record) {
		getSqlMapClientTemplate().insert(
				"t_shop_category_goods_link.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKey(TShopCategoryGoodsLink record) {
		int rows = getSqlMapClientTemplate()
				.update("t_shop_category_goods_link.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKeySelective(TShopCategoryGoodsLink record) {
		int rows = getSqlMapClientTemplate()
				.update("t_shop_category_goods_link.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public List selectByExample(TShopCategoryGoodsLinkExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_shop_category_goods_link.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TShopCategoryGoodsLink selectByPrimaryKey(Integer categoryGoodsId) {
		TShopCategoryGoodsLink key = new TShopCategoryGoodsLink();
		key.setCategoryGoodsId(categoryGoodsId);
		TShopCategoryGoodsLink record = (TShopCategoryGoodsLink) getSqlMapClientTemplate()
				.queryForObject(
						"t_shop_category_goods_link.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByExample(TShopCategoryGoodsLinkExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_shop_category_goods_link.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByPrimaryKey(Integer categoryGoodsId) {
		TShopCategoryGoodsLink key = new TShopCategoryGoodsLink();
		key.setCategoryGoodsId(categoryGoodsId);
		int rows = getSqlMapClientTemplate()
				.delete("t_shop_category_goods_link.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int countByExample(TShopCategoryGoodsLinkExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_shop_category_goods_link.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExampleSelective(TShopCategoryGoodsLink record,
			TShopCategoryGoodsLinkExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_shop_category_goods_link.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExample(TShopCategoryGoodsLink record,
			TShopCategoryGoodsLinkExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_shop_category_goods_link.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_shop_category_goods_link
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private static class UpdateByExampleParms extends
			TShopCategoryGoodsLinkExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TShopCategoryGoodsLinkExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}