package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TShopCategoryGoods;
import app.cn.qtt.bm.model.TShopCategoryGoodsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TShopCategoryGoodsDAOImpl extends SqlMapClientDaoSupport implements TShopCategoryGoodsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopCategoryGoodsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TShopCategoryGoods record) {
        getSqlMapClientTemplate().insert("t_shop_category_goods.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TShopCategoryGoods record) {
        int rows = getSqlMapClientTemplate().update("t_shop_category_goods.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TShopCategoryGoods record) {
        int rows = getSqlMapClientTemplate().update("t_shop_category_goods.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TShopCategoryGoodsExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_shop_category_goods.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopCategoryGoods selectByPrimaryKey(Integer categoryId) {
        TShopCategoryGoods key = new TShopCategoryGoods();
        key.setCategoryId(categoryId);
        TShopCategoryGoods record = (TShopCategoryGoods) getSqlMapClientTemplate().queryForObject("t_shop_category_goods.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TShopCategoryGoodsExample example) {
        int rows = getSqlMapClientTemplate().delete("t_shop_category_goods.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer categoryId) {
        TShopCategoryGoods key = new TShopCategoryGoods();
        key.setCategoryId(categoryId);
        int rows = getSqlMapClientTemplate().delete("t_shop_category_goods.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TShopCategoryGoodsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_shop_category_goods.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TShopCategoryGoods record, TShopCategoryGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_category_goods.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TShopCategoryGoods record, TShopCategoryGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_category_goods.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_shop_category_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TShopCategoryGoodsExample {
        private Object record;

        public UpdateByExampleParms(Object record, TShopCategoryGoodsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}