package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TShopGoodsTime;
import app.cn.qtt.bm.model.TShopGoodsTimeExample;
import java.util.List;

public interface TShopGoodsTimeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    void insert(TShopGoodsTime record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKey(TShopGoodsTime record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKeySelective(TShopGoodsTime record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    List selectByExample(TShopGoodsTimeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    TShopGoodsTime selectByPrimaryKey(Integer shopGoodsTimeId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByExample(TShopGoodsTimeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByPrimaryKey(Integer shopGoodsTimeId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int countByExample(TShopGoodsTimeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExampleSelective(TShopGoodsTime record, TShopGoodsTimeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExample(TShopGoodsTime record, TShopGoodsTimeExample example);
}