package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TShopGoodsDeal;
import app.cn.qtt.bm.model.TShopGoodsDealExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TShopGoodsDealDAOImpl extends SqlMapClientDaoSupport implements TShopGoodsDealDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopGoodsDealDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TShopGoodsDeal record) {
        getSqlMapClientTemplate().insert("t_shop_goods_deal.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TShopGoodsDeal record) {
        int rows = getSqlMapClientTemplate().update("t_shop_goods_deal.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TShopGoodsDeal record) {
        int rows = getSqlMapClientTemplate().update("t_shop_goods_deal.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TShopGoodsDealExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_shop_goods_deal.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopGoodsDeal selectByPrimaryKey(Integer shopGoodsDealId) {
        TShopGoodsDeal key = new TShopGoodsDeal();
        key.setShopGoodsDealId(shopGoodsDealId);
        TShopGoodsDeal record = (TShopGoodsDeal) getSqlMapClientTemplate().queryForObject("t_shop_goods_deal.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TShopGoodsDealExample example) {
        int rows = getSqlMapClientTemplate().delete("t_shop_goods_deal.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer shopGoodsDealId) {
        TShopGoodsDeal key = new TShopGoodsDeal();
        key.setShopGoodsDealId(shopGoodsDealId);
        int rows = getSqlMapClientTemplate().delete("t_shop_goods_deal.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TShopGoodsDealExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_shop_goods_deal.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TShopGoodsDeal record, TShopGoodsDealExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_goods_deal.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TShopGoodsDeal record, TShopGoodsDealExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_goods_deal.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_shop_goods_deal
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TShopGoodsDealExample {
        private Object record;

        public UpdateByExampleParms(Object record, TShopGoodsDealExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}