package app.cn.qtt.bm.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import app.cn.qtt.bm.model.NewTShopGoods;
import app.cn.qtt.bm.model.TShopGoods;
import app.cn.qtt.bm.model.TShopGoodsExample;

public class TShopGoodsDAOImpl extends SqlMapClientDaoSupport implements TShopGoodsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopGoodsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int insert(TShopGoods record) {
    	return (Integer) getSqlMapClientTemplate().insert("t_shop_goods.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TShopGoods record) {
        int rows = getSqlMapClientTemplate().update("t_shop_goods.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TShopGoods record) {
        int rows = getSqlMapClientTemplate().update("t_shop_goods.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TShopGoodsExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_shop_goods.abatorgenerated_selectByExample", example);
        return list;
    }

    public List selectImageByExample(TShopGoodsExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_shop_goods.abatorgenerated_selectImageByExample", example);
        return list;
    }
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopGoods selectByPrimaryKey(Integer shopGoodsId) {
        TShopGoods key = new TShopGoods();
        key.setShopGoodsId(shopGoodsId);
        TShopGoods record = (TShopGoods) getSqlMapClientTemplate().queryForObject("t_shop_goods.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TShopGoodsExample example) {
        int rows = getSqlMapClientTemplate().delete("t_shop_goods.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer shopGoodsId) {
        TShopGoods key = new TShopGoods();
        key.setShopGoodsId(shopGoodsId);
        int rows = getSqlMapClientTemplate().delete("t_shop_goods.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TShopGoodsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_shop_goods.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TShopGoods record, TShopGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_goods.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TShopGoods record, TShopGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_goods.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_shop_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TShopGoodsExample {
        private Object record;
        private int currentPage;
        private int pageRecords;
        private Integer categoryId;
        private List<String> timeCodeList;
        private Integer shopId;

        public UpdateByExampleParms(Object record, TShopGoodsExample example) {
            super(example);
            this.record = record;
        }
        
        public UpdateByExampleParms(TShopGoodsExample example,
                int currentPage,
                int pageRecords,
                Integer categoryId,
                List<String> timeCodeList,
                Integer shopId) {
			super(example);
			this.currentPage = currentPage;
			this.pageRecords = pageRecords;
			this.categoryId = categoryId;
			this.timeCodeList = timeCodeList;
			this.shopId = shopId;
		}

        public Object getRecord() {
            return record;
        }
		/**
		 * @return the currentPage
		 */
		public int getCurrentPage() {
			return currentPage;
		}
		/**
		 * @return the pageRecords
		 */
		public int getPageRecords() {
			return pageRecords;
		}
		/**
		 * @return the categoryId
		 */
		public Integer getCategoryId() {
			return categoryId;
		}
		/**
		 * @return the timeCodeList
		 */
		public Object getTimeCodeList() {
			return timeCodeList;
		}

		/**
		 * @return the shopId
		 */
		public Integer getShopId() {
			return shopId;
		}

    }

	@Override
	public List<NewTShopGoods> selectPagesByExample(int currentPage,
			int pageRecords, Integer categoryId, List<String> timeCodeList,
			Integer shopId, TShopGoodsExample example) {
		Map<String,Object> params = new HashMap<String, Object>();
		
		params.put("currentPage", currentPage);
		params.put("pageRecords", pageRecords);
		params.put("categoryId", categoryId);
		params.put("timeCodeList", timeCodeList);
		params.put("shopId", shopId);
		
		return getSqlMapClientTemplate().queryForList(
				"t_shop_goods.select_by_category_and_supplytime", params);
	}

	@Override
	public int countTotalRecordsByExample(Integer categoryId, List<String> timeCodeList, Integer shopId,
			TShopGoodsExample example) {
		Map<String,Object> params = new HashMap<String, Object>();
		
		params.put("categoryId", categoryId);
		params.put("timeCodeList", timeCodeList);
		params.put("shopId", shopId);
		
		return (Integer) getSqlMapClientTemplate().queryForObject(
				"t_shop_goods.select_by_category_and_supplytime_count", params);
	}

}