package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TShopGoodsTime;
import app.cn.qtt.bm.model.TShopGoodsTimeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TShopGoodsTimeDAOImpl extends SqlMapClientDaoSupport implements TShopGoodsTimeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopGoodsTimeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TShopGoodsTime record) {
        getSqlMapClientTemplate().insert("t_shop_goods_time.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TShopGoodsTime record) {
        int rows = getSqlMapClientTemplate().update("t_shop_goods_time.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TShopGoodsTime record) {
        int rows = getSqlMapClientTemplate().update("t_shop_goods_time.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TShopGoodsTimeExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_shop_goods_time.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopGoodsTime selectByPrimaryKey(Integer shopGoodsTimeId) {
        TShopGoodsTime key = new TShopGoodsTime();
        key.setShopGoodsTimeId(shopGoodsTimeId);
        TShopGoodsTime record = (TShopGoodsTime) getSqlMapClientTemplate().queryForObject("t_shop_goods_time.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TShopGoodsTimeExample example) {
        int rows = getSqlMapClientTemplate().delete("t_shop_goods_time.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer shopGoodsTimeId) {
        TShopGoodsTime key = new TShopGoodsTime();
        key.setShopGoodsTimeId(shopGoodsTimeId);
        int rows = getSqlMapClientTemplate().delete("t_shop_goods_time.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TShopGoodsTimeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_shop_goods_time.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TShopGoodsTime record, TShopGoodsTimeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_goods_time.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TShopGoodsTime record, TShopGoodsTimeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_shop_goods_time.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_shop_goods_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TShopGoodsTimeExample {
        private Object record;

        public UpdateByExampleParms(Object record, TShopGoodsTimeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}