package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysMenuFuncInfo;
import app.cn.qtt.bm.model.TSysMenuFuncInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysMenuFuncInfoDAOImpl extends SqlMapClientDaoSupport implements TSysMenuFuncInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TSysMenuFuncInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void insert(TSysMenuFuncInfo record) {
		getSqlMapClientTemplate().insert(
				"t_sys_menu_func_info.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKey(TSysMenuFuncInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_menu_func_info.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKeySelective(TSysMenuFuncInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("t_sys_menu_func_info.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public List selectByExample(TSysMenuFuncInfoExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"t_sys_menu_func_info.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TSysMenuFuncInfo selectByPrimaryKey(Integer funcId) {
		TSysMenuFuncInfo key = new TSysMenuFuncInfo();
		key.setFuncId(funcId);
		TSysMenuFuncInfo record = (TSysMenuFuncInfo) getSqlMapClientTemplate()
				.queryForObject(
						"t_sys_menu_func_info.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByExample(TSysMenuFuncInfoExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("t_sys_menu_func_info.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByPrimaryKey(Integer funcId) {
		TSysMenuFuncInfo key = new TSysMenuFuncInfo();
		key.setFuncId(funcId);
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_menu_func_info.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int countByExample(TSysMenuFuncInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_sys_menu_func_info.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExampleSelective(TSysMenuFuncInfo record,
			TSysMenuFuncInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_sys_menu_func_info.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExample(TSysMenuFuncInfo record,
			TSysMenuFuncInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_menu_func_info.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_menu_func_info
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private static class UpdateByExampleParms extends TSysMenuFuncInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TSysMenuFuncInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}