package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysLinkUserRole;
import app.cn.qtt.bm.model.TSysLinkUserRoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysLinkUserRoleDAOImpl extends SqlMapClientDaoSupport implements TSysLinkUserRoleDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TSysLinkUserRoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void insert(TSysLinkUserRole record) {
		getSqlMapClientTemplate().insert(
				"t_sys_link_user_role.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKey(TSysLinkUserRole record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_link_user_role.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKeySelective(TSysLinkUserRole record) {
		int rows = getSqlMapClientTemplate()
				.update("t_sys_link_user_role.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public List selectByExample(TSysLinkUserRoleExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"t_sys_link_user_role.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TSysLinkUserRole selectByPrimaryKey(Integer linkUserRoleId) {
		TSysLinkUserRole key = new TSysLinkUserRole();
		key.setLinkUserRoleId(linkUserRoleId);
		TSysLinkUserRole record = (TSysLinkUserRole) getSqlMapClientTemplate()
				.queryForObject(
						"t_sys_link_user_role.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByExample(TSysLinkUserRoleExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("t_sys_link_user_role.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByPrimaryKey(Integer linkUserRoleId) {
		TSysLinkUserRole key = new TSysLinkUserRole();
		key.setLinkUserRoleId(linkUserRoleId);
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_link_user_role.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int countByExample(TSysLinkUserRoleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_sys_link_user_role.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExampleSelective(TSysLinkUserRole record,
			TSysLinkUserRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_sys_link_user_role.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExample(TSysLinkUserRole record,
			TSysLinkUserRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_link_user_role.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_link_user_role
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private static class UpdateByExampleParms extends TSysLinkUserRoleExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TSysLinkUserRoleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}