package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysCaptcha;
import app.cn.qtt.bm.model.TSysCaptchaExample;
import java.util.List;

public interface TSysCaptchaDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    void insert(TSysCaptcha record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKey(TSysCaptcha record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByPrimaryKeySelective(TSysCaptcha record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    List selectByExample(TSysCaptchaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    TSysCaptcha selectByPrimaryKey(Integer captchaId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByExample(TSysCaptchaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int deleteByPrimaryKey(Integer captchaId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int countByExample(TSysCaptchaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExampleSelective(TSysCaptcha record, TSysCaptchaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    int updateByExample(TSysCaptcha record, TSysCaptchaExample example);
}