package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysCodeMetadata;
import app.cn.qtt.bm.model.TSysCodeMetadataExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysCodeMetadataDAOImpl extends SqlMapClientDaoSupport implements TSysCodeMetadataDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysCodeMetadataDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSysCodeMetadata record) {
        getSqlMapClientTemplate().insert("t_sys_code_metadata.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TSysCodeMetadataExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sys_code_metadata.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSysCodeMetadataExample example) {
        int rows = getSqlMapClientTemplate().delete("t_sys_code_metadata.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSysCodeMetadataExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_sys_code_metadata.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSysCodeMetadata record, TSysCodeMetadataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_code_metadata.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TSysCodeMetadata record, TSysCodeMetadataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_code_metadata.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_sys_code_metadata
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSysCodeMetadataExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSysCodeMetadataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}