package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysCodeTree;
import app.cn.qtt.bm.model.TSysCodeTreeExample;
import app.cn.qtt.bm.model.TSysCodeTreeKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysCodeTreeDAOImpl extends SqlMapClientDaoSupport implements TSysCodeTreeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysCodeTreeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSysCodeTree record) {
        getSqlMapClientTemplate().insert("t_sys_code_tree.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TSysCodeTree record) {
        int rows = getSqlMapClientTemplate().update("t_sys_code_tree.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSysCodeTree record) {
        int rows = getSqlMapClientTemplate().update("t_sys_code_tree.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TSysCodeTreeExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sys_code_tree.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysCodeTree selectByPrimaryKey(TSysCodeTreeKey key) {
        TSysCodeTree record = (TSysCodeTree) getSqlMapClientTemplate().queryForObject("t_sys_code_tree.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSysCodeTreeExample example) {
        int rows = getSqlMapClientTemplate().delete("t_sys_code_tree.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(TSysCodeTreeKey key) {
        int rows = getSqlMapClientTemplate().delete("t_sys_code_tree.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSysCodeTreeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_sys_code_tree.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSysCodeTree record, TSysCodeTreeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_code_tree.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TSysCodeTree record, TSysCodeTreeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_code_tree.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_sys_code_tree
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSysCodeTreeExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSysCodeTreeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}