package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysFile;
import app.cn.qtt.bm.model.TSysFileExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysFileDAOImpl extends SqlMapClientDaoSupport implements TSysFileDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public TSysFileDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int insert(TSysFile record) {
    	return (Integer)getSqlMapClientTemplate().insert("t_sys_file.abatorgenerated_insert", record);
    }

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int updateByPrimaryKey(TSysFile record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_file.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int updateByPrimaryKeySelective(TSysFile record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_file.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public List selectByExample(TSysFileExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_sys_file.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public TSysFile selectByPrimaryKey(Integer fileId) {
		TSysFile key = new TSysFile();
		key.setFileId(fileId);
		TSysFile record = (TSysFile) getSqlMapClientTemplate().queryForObject(
				"t_sys_file.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int deleteByExample(TSysFileExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_file.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int deleteByPrimaryKey(Integer fileId) {
		TSysFile key = new TSysFile();
		key.setFileId(fileId);
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_file.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int countByExample(TSysFileExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_sys_file.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int updateByExampleSelective(TSysFile record, TSysFileExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_file.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public int updateByExample(TSysFile record, TSysFileExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_file.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_file
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private static class UpdateByExampleParms extends TSysFileExample {
		private Object record;

		public UpdateByExampleParms(Object record, TSysFileExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}