package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysCaptcha;
import app.cn.qtt.bm.model.TSysCaptchaExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysCaptchaDAOImpl extends SqlMapClientDaoSupport implements TSysCaptchaDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysCaptchaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSysCaptcha record) {
        getSqlMapClientTemplate().insert("t_sys_captcha.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKey(TSysCaptcha record) {
        int rows = getSqlMapClientTemplate().update("t_sys_captcha.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSysCaptcha record) {
        int rows = getSqlMapClientTemplate().update("t_sys_captcha.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExample(TSysCaptchaExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sys_captcha.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysCaptcha selectByPrimaryKey(Integer captchaId) {
        TSysCaptcha key = new TSysCaptcha();
        key.setCaptchaId(captchaId);
        TSysCaptcha record = (TSysCaptcha) getSqlMapClientTemplate().queryForObject("t_sys_captcha.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSysCaptchaExample example) {
        int rows = getSqlMapClientTemplate().delete("t_sys_captcha.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer captchaId) {
        TSysCaptcha key = new TSysCaptcha();
        key.setCaptchaId(captchaId);
        int rows = getSqlMapClientTemplate().delete("t_sys_captcha.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSysCaptchaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_sys_captcha.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSysCaptcha record, TSysCaptchaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_captcha.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExample(TSysCaptcha record, TSysCaptchaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_captcha.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_sys_captcha
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSysCaptchaExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSysCaptchaExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}