package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysParameter;
import app.cn.qtt.bm.model.TSysParameterExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysParameterDAOImpl extends SqlMapClientDaoSupport implements TSysParameterDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysParameterDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void insert(TSysParameter record) {
        getSqlMapClientTemplate().insert("t_sys_parameter.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(TSysParameter record) {
        int rows = getSqlMapClientTemplate().update("t_sys_parameter.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(TSysParameter record) {
        int rows = getSqlMapClientTemplate().update("t_sys_parameter.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSysParameter record) {
        int rows = getSqlMapClientTemplate().update("t_sys_parameter.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExampleWithoutBLOBs(TSysParameterExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sys_parameter.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List selectByExampleWithBLOBs(TSysParameterExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sys_parameter.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TSysParameter selectByPrimaryKey(Integer paramId) {
        TSysParameter key = new TSysParameter();
        key.setParamId(paramId);
        TSysParameter record = (TSysParameter) getSqlMapClientTemplate().queryForObject("t_sys_parameter.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByExample(TSysParameterExample example) {
        int rows = getSqlMapClientTemplate().delete("t_sys_parameter.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer paramId) {
        TSysParameter key = new TSysParameter();
        key.setParamId(paramId);
        int rows = getSqlMapClientTemplate().delete("t_sys_parameter.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int countByExample(TSysParameterExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_sys_parameter.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleSelective(TSysParameter record, TSysParameterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_parameter.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleWithBLOBs(TSysParameter record, TSysParameterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_parameter.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public int updateByExampleWithoutBLOBs(TSysParameter record, TSysParameterExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_parameter.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_sys_parameter
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSysParameterExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSysParameterExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}