package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysUserSeq;
import app.cn.qtt.bm.model.TSysUserSeqExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysUserSeqDAOImpl extends SqlMapClientDaoSupport implements TSysUserSeqDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public TSysUserSeqDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public void insert(TSysUserSeq record) {
        getSqlMapClientTemplate().insert("t_sys_user_seq.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int updateByPrimaryKey(TSysUserSeq record) {
        int rows = getSqlMapClientTemplate().update("t_sys_user_seq.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int updateByPrimaryKeySelective(TSysUserSeq record) {
        int rows = getSqlMapClientTemplate().update("t_sys_user_seq.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public List selectByExample(TSysUserSeqExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sys_user_seq.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public TSysUserSeq selectByPrimaryKey(Integer id) {
        TSysUserSeq key = new TSysUserSeq();
        key.setId(id);
        TSysUserSeq record = (TSysUserSeq) getSqlMapClientTemplate().queryForObject("t_sys_user_seq.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int deleteByExample(TSysUserSeqExample example) {
        int rows = getSqlMapClientTemplate().delete("t_sys_user_seq.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        TSysUserSeq key = new TSysUserSeq();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_sys_user_seq.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int countByExample(TSysUserSeqExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_sys_user_seq.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int updateByExampleSelective(TSysUserSeq record, TSysUserSeqExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_user_seq.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    public int updateByExample(TSysUserSeq record, TSysUserSeqExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sys_user_seq.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_sys_user_seq
     *
     * @abatorgenerated Mon Jun 17 18:06:10 CST 2013
     */
    private static class UpdateByExampleParms extends TSysUserSeqExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSysUserSeqExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    
    /**
	* 方法名称:      insertSeqByType  
	* 方法描述:      
	* @param record
	* @return        
	* @Author:      linch
	* @Create Date: 2013-4-8 下午10:13:08
	*/ 
	 
	@Override
	public Integer insertSeqByType(TSysUserSeq record) {
		Integer count = (Integer)  getSqlMapClientTemplate().insert("t_sys_user_seq.insert_new_seq_by_type",record);
        return count;
		
	}
}