package app.cn.qtt.bm.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import app.cn.qtt.bm.model.TSysRoleInfo;
import app.cn.qtt.bm.model.TSysRoleInfoExample;
import app.cn.qtt.bm.model.TSysUserInfo;

public class TSysRoleInfoDAOImpl extends SqlMapClientDaoSupport implements TSysRoleInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public TSysRoleInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public void insert(TSysRoleInfo record) {
		getSqlMapClientTemplate().insert(
				"t_sys_role_info.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int updateByPrimaryKey(TSysRoleInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_role_info.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int updateByPrimaryKeySelective(TSysRoleInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_role_info.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public List selectByExample(TSysRoleInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_sys_role_info.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public TSysRoleInfo selectByPrimaryKey(Integer roleId) {
		TSysRoleInfo key = new TSysRoleInfo();
		key.setRoleId(roleId);
		TSysRoleInfo record = (TSysRoleInfo) getSqlMapClientTemplate()
				.queryForObject(
						"t_sys_role_info.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int deleteByExample(TSysRoleInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_role_info.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int deleteByPrimaryKey(Integer roleId) {
		TSysRoleInfo key = new TSysRoleInfo();
		key.setRoleId(roleId);
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_role_info.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int countByExample(TSysRoleInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_sys_role_info.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int updateByExampleSelective(TSysRoleInfo record,
			TSysRoleInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_role_info.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	public int updateByExample(TSysRoleInfo record, TSysRoleInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_role_info.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_role_info
	 * @abatorgenerated  Sat Jun 08 17:03:33 CST 2013
	 */
	private static class UpdateByExampleParms extends TSysRoleInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, TSysRoleInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	public List<TSysRoleInfo> selectRoleByUserCode(TSysUserInfo record) {		
		return getSqlMapClientTemplate().queryForList("t_sys_role_info.selectRoleByUserCode", record);
	}
}