package app.cn.qtt.bm.dao;

import app.cn.qtt.bm.model.TSysLinkRoleMenu;
import app.cn.qtt.bm.model.TSysLinkRoleMenuExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSysLinkRoleMenuDAOImpl extends SqlMapClientDaoSupport implements TSysLinkRoleMenuDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TSysLinkRoleMenuDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void insert(TSysLinkRoleMenu record) {
		getSqlMapClientTemplate().insert(
				"t_sys_link_role_menu.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKey(TSysLinkRoleMenu record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_link_role_menu.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByPrimaryKeySelective(TSysLinkRoleMenu record) {
		int rows = getSqlMapClientTemplate()
				.update("t_sys_link_role_menu.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public List selectByExample(TSysLinkRoleMenuExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"t_sys_link_role_menu.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public TSysLinkRoleMenu selectByPrimaryKey(Integer linkRoleMenuId) {
		TSysLinkRoleMenu key = new TSysLinkRoleMenu();
		key.setLinkRoleMenuId(linkRoleMenuId);
		TSysLinkRoleMenu record = (TSysLinkRoleMenu) getSqlMapClientTemplate()
				.queryForObject(
						"t_sys_link_role_menu.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByExample(TSysLinkRoleMenuExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("t_sys_link_role_menu.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int deleteByPrimaryKey(Integer linkRoleMenuId) {
		TSysLinkRoleMenu key = new TSysLinkRoleMenu();
		key.setLinkRoleMenuId(linkRoleMenuId);
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_link_role_menu.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int countByExample(TSysLinkRoleMenuExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_sys_link_role_menu.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExampleSelective(TSysLinkRoleMenu record,
			TSysLinkRoleMenuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_sys_link_role_menu.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public int updateByExample(TSysLinkRoleMenu record,
			TSysLinkRoleMenuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_link_role_menu.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_link_role_menu
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private static class UpdateByExampleParms extends TSysLinkRoleMenuExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TSysLinkRoleMenuExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}