package app.cn.qtt.bm.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import app.cn.qtt.bm.model.TSysUserInfo;
import app.cn.qtt.bm.model.TSysUserInfoExample;

public class TSysUserInfoDAOImpl extends SqlMapClientDaoSupport implements TSysUserInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public TSysUserInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public void insert(TSysUserInfo record) {
		getSqlMapClientTemplate().insert(
				"t_sys_user_info.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int updateByPrimaryKey(TSysUserInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_user_info.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int updateByPrimaryKeySelective(TSysUserInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_user_info.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public List selectByExample(TSysUserInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_sys_user_info.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public TSysUserInfo selectByPrimaryKey(Integer userId) {
		TSysUserInfo key = new TSysUserInfo();
		key.setUserId(userId);
		TSysUserInfo record = (TSysUserInfo) getSqlMapClientTemplate()
				.queryForObject(
						"t_sys_user_info.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int deleteByExample(TSysUserInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_user_info.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int deleteByPrimaryKey(Integer userId) {
		TSysUserInfo key = new TSysUserInfo();
		key.setUserId(userId);
		int rows = getSqlMapClientTemplate().delete(
				"t_sys_user_info.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int countByExample(TSysUserInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_sys_user_info.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int updateByExampleSelective(TSysUserInfo record,
			TSysUserInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_user_info.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	public int updateByExample(TSysUserInfo record, TSysUserInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_user_info.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_user_info
	 * @abatorgenerated  Thu Jul 04 11:01:40 CST 2013
	 */
	private static class UpdateByExampleParms extends TSysUserInfoExample {
		private Object record;
		private int currentPage;
        private int pageRecords;
        private String dayTime;

		public UpdateByExampleParms(Object record, TSysUserInfoExample example) {
			super(example);
			this.record = record;
		}
		
		 public UpdateByExampleParms(TSysUserInfoExample example,
	                int currentPage,
	                int pageRecords,
	                String dayTime) {
				super(example);
				this.currentPage = currentPage;
				this.pageRecords = pageRecords;
				this.dayTime = dayTime;
			}

		public Object getRecord() {
			return record;
		}
		/**
		 * @return the currentPage
		 */
		public int getCurrentPage() {
			return currentPage;
		}
		/**
		 * @return the pageRecords
		 */
		public int getPageRecords() {
			return pageRecords;
		}
		/**
		 * @return the dateTime
		 */
		public String getDayTime() {
			return dayTime;
		}
	}

	@Override
	public Integer selectCountsByExample(TSysUserInfoExample example) {
		Integer counts=(Integer)getSqlMapClientTemplate().queryForObject("t_sys_user_info.selectCountsByExample",example);
		return counts;
	}

	@Override
	public List<TSysUserInfo> selectPagesByExample(TSysUserInfoExample example,
			int currentPage, int pageSize) {
		List<TSysUserInfo> list = (List<TSysUserInfo>) getSqlMapClientTemplate()
		.queryForList(
				"t_sys_user_info.abatorgenerated_selectByExample",
				example,(currentPage-1)*pageSize,pageSize);
		return list;
	}

	/**
	 * Add by jjf 2013-4-1
	 * ??????????List ????????
	 */
	public int updateUserStatusByExample(TSysUserInfo record, TSysUserInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_sys_user_info.forbidBatchUser_updateByUserCodeList", parms);
		return rows;
	}
	//????????????,?????
	public List<TSysUserInfo> selectByUserProperties(TSysUserInfo record,int currentPage,int pageSize) {
		List<TSysUserInfo> list=getSqlMapClientTemplate().queryForList("t_sys_user_info.selectByUserProperties",record,(currentPage-1)*pageSize,pageSize);
		return list;
	}
	//????????????,????????
	public List<TSysUserInfo> selectByUserProperties(TSysUserInfo record) {
		List<TSysUserInfo> list=getSqlMapClientTemplate().queryForList("t_sys_user_info.selectByUserProperties",record);
		return list;
	}
	//????????????,????????
	public int selectCountsByUserProperties(TSysUserInfo record) {
		Integer resultNum=(Integer)getSqlMapClientTemplate().queryForObject("t_sys_user_info.selectCountByUserProperties",record);
		return resultNum;
	}

	//???????????
	public List<TSysUserInfo> fuzzySelectByUserProperties(TSysUserInfo record) {
		List<TSysUserInfo> list=getSqlMapClientTemplate().queryForList("t_sys_user_info.fuzzySelectByUserProperties",record);
		return list;
	}

	//???????????,?????
	public List<TSysUserInfo> fuzzySelectByUserProperties(TSysUserInfo record,
			int currentPage, int pageSize) {
		List<TSysUserInfo> list=getSqlMapClientTemplate().queryForList("t_sys_user_info.fuzzySelectByUserProperties",record,(currentPage-1)*pageSize,pageSize);
		return list;
	}

	
	public int fuzzySelectCountsByUserProperties(TSysUserInfo record) {
		Integer resultNum=(Integer)getSqlMapClientTemplate().queryForObject("t_sys_user_info.fuzzySelectCountByUserProperties",record);
		return resultNum;
	}


	@Override
	public List<TSysUserInfo> selectIllegalUser(String dayTime, int currentPage, int pageRecords) {
		TSysUserInfoExample example = new TSysUserInfoExample();
		UpdateByExampleParms parms = new UpdateByExampleParms(example,currentPage,pageRecords,dayTime);
		
		List<TSysUserInfo> list=getSqlMapClientTemplate().queryForList("t_sys_user_info.selectIllegalUser",parms);
		return list;
	}

	@Override
	public int selectIllegalUserCount(String dayTime) {
		TSysUserInfoExample example = new TSysUserInfoExample();
		UpdateByExampleParms parms = new UpdateByExampleParms(example,0,0,dayTime);
		
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("t_sys_user_info.selectIllegalUserCount",parms);
		return count.intValue();
	}

	/**
	 * @see app.cn.qtt.bm.dao.TSysUserInfoDAO#passwordOverTime()
	 * @author Gabriel
	 * @createtime 2013-8-24 下午9:37:34
	 */
	@Override
	public int passwordOverTime() {
		int rows = getSqlMapClientTemplate().update(
				"t_sys_user_info.passwordOverTime");
		return rows;
	}
	
}