package app.cn.qtt.bm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TLogUserAccessExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TLogUserAccessExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected TLogUserAccessExample(TLogUserAccessExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_log_user_access
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andUserLogIdIsNull() {
            addCriterion("user_log_id is null");
            return this;
        }

        public Criteria andUserLogIdIsNotNull() {
            addCriterion("user_log_id is not null");
            return this;
        }

        public Criteria andUserLogIdEqualTo(Integer value) {
            addCriterion("user_log_id =", value, "userLogId");
            return this;
        }

        public Criteria andUserLogIdNotEqualTo(Integer value) {
            addCriterion("user_log_id <>", value, "userLogId");
            return this;
        }

        public Criteria andUserLogIdGreaterThan(Integer value) {
            addCriterion("user_log_id >", value, "userLogId");
            return this;
        }

        public Criteria andUserLogIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_log_id >=", value, "userLogId");
            return this;
        }

        public Criteria andUserLogIdLessThan(Integer value) {
            addCriterion("user_log_id <", value, "userLogId");
            return this;
        }

        public Criteria andUserLogIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_log_id <=", value, "userLogId");
            return this;
        }

        public Criteria andUserLogIdIn(List values) {
            addCriterion("user_log_id in", values, "userLogId");
            return this;
        }

        public Criteria andUserLogIdNotIn(List values) {
            addCriterion("user_log_id not in", values, "userLogId");
            return this;
        }

        public Criteria andUserLogIdBetween(Integer value1, Integer value2) {
            addCriterion("user_log_id between", value1, value2, "userLogId");
            return this;
        }

        public Criteria andUserLogIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_log_id not between", value1, value2, "userLogId");
            return this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("user_code is null");
            return this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("user_code is not null");
            return this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("user_code =", value, "userCode");
            return this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("user_code <>", value, "userCode");
            return this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("user_code >", value, "userCode");
            return this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("user_code >=", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("user_code <", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("user_code <=", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("user_code like", value, "userCode");
            return this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("user_code not like", value, "userCode");
            return this;
        }

        public Criteria andUserCodeIn(List values) {
            addCriterion("user_code in", values, "userCode");
            return this;
        }

        public Criteria andUserCodeNotIn(List values) {
            addCriterion("user_code not in", values, "userCode");
            return this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("user_code between", value1, value2, "userCode");
            return this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("user_code not between", value1, value2, "userCode");
            return this;
        }

        public Criteria andUserClientIpIsNull() {
            addCriterion("user_client_ip is null");
            return this;
        }

        public Criteria andUserClientIpIsNotNull() {
            addCriterion("user_client_ip is not null");
            return this;
        }

        public Criteria andUserClientIpEqualTo(String value) {
            addCriterion("user_client_ip =", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpNotEqualTo(String value) {
            addCriterion("user_client_ip <>", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpGreaterThan(String value) {
            addCriterion("user_client_ip >", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpGreaterThanOrEqualTo(String value) {
            addCriterion("user_client_ip >=", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpLessThan(String value) {
            addCriterion("user_client_ip <", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpLessThanOrEqualTo(String value) {
            addCriterion("user_client_ip <=", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpLike(String value) {
            addCriterion("user_client_ip like", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpNotLike(String value) {
            addCriterion("user_client_ip not like", value, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpIn(List values) {
            addCriterion("user_client_ip in", values, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpNotIn(List values) {
            addCriterion("user_client_ip not in", values, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpBetween(String value1, String value2) {
            addCriterion("user_client_ip between", value1, value2, "userClientIp");
            return this;
        }

        public Criteria andUserClientIpNotBetween(String value1, String value2) {
            addCriterion("user_client_ip not between", value1, value2, "userClientIp");
            return this;
        }

        public Criteria andUserServerIpIsNull() {
            addCriterion("user_server_ip is null");
            return this;
        }

        public Criteria andUserServerIpIsNotNull() {
            addCriterion("user_server_ip is not null");
            return this;
        }

        public Criteria andUserServerIpEqualTo(String value) {
            addCriterion("user_server_ip =", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpNotEqualTo(String value) {
            addCriterion("user_server_ip <>", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpGreaterThan(String value) {
            addCriterion("user_server_ip >", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("user_server_ip >=", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpLessThan(String value) {
            addCriterion("user_server_ip <", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpLessThanOrEqualTo(String value) {
            addCriterion("user_server_ip <=", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpLike(String value) {
            addCriterion("user_server_ip like", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpNotLike(String value) {
            addCriterion("user_server_ip not like", value, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpIn(List values) {
            addCriterion("user_server_ip in", values, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpNotIn(List values) {
            addCriterion("user_server_ip not in", values, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpBetween(String value1, String value2) {
            addCriterion("user_server_ip between", value1, value2, "userServerIp");
            return this;
        }

        public Criteria andUserServerIpNotBetween(String value1, String value2) {
            addCriterion("user_server_ip not between", value1, value2, "userServerIp");
            return this;
        }

        public Criteria andUserAgentIsNull() {
            addCriterion("user_agent is null");
            return this;
        }

        public Criteria andUserAgentIsNotNull() {
            addCriterion("user_agent is not null");
            return this;
        }

        public Criteria andUserAgentEqualTo(String value) {
            addCriterion("user_agent =", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentNotEqualTo(String value) {
            addCriterion("user_agent <>", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentGreaterThan(String value) {
            addCriterion("user_agent >", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentGreaterThanOrEqualTo(String value) {
            addCriterion("user_agent >=", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentLessThan(String value) {
            addCriterion("user_agent <", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentLessThanOrEqualTo(String value) {
            addCriterion("user_agent <=", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentLike(String value) {
            addCriterion("user_agent like", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentNotLike(String value) {
            addCriterion("user_agent not like", value, "userAgent");
            return this;
        }

        public Criteria andUserAgentIn(List values) {
            addCriterion("user_agent in", values, "userAgent");
            return this;
        }

        public Criteria andUserAgentNotIn(List values) {
            addCriterion("user_agent not in", values, "userAgent");
            return this;
        }

        public Criteria andUserAgentBetween(String value1, String value2) {
            addCriterion("user_agent between", value1, value2, "userAgent");
            return this;
        }

        public Criteria andUserAgentNotBetween(String value1, String value2) {
            addCriterion("user_agent not between", value1, value2, "userAgent");
            return this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("session_id is null");
            return this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("session_id is not null");
            return this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("session_id =", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("session_id <>", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("session_id >", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("session_id >=", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("session_id <", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("session_id <=", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("session_id like", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("session_id not like", value, "sessionId");
            return this;
        }

        public Criteria andSessionIdIn(List values) {
            addCriterion("session_id in", values, "sessionId");
            return this;
        }

        public Criteria andSessionIdNotIn(List values) {
            addCriterion("session_id not in", values, "sessionId");
            return this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("session_id between", value1, value2, "sessionId");
            return this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("session_id not between", value1, value2, "sessionId");
            return this;
        }

        public Criteria andCookieIdIsNull() {
            addCriterion("cookie_id is null");
            return this;
        }

        public Criteria andCookieIdIsNotNull() {
            addCriterion("cookie_id is not null");
            return this;
        }

        public Criteria andCookieIdEqualTo(String value) {
            addCriterion("cookie_id =", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdNotEqualTo(String value) {
            addCriterion("cookie_id <>", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdGreaterThan(String value) {
            addCriterion("cookie_id >", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdGreaterThanOrEqualTo(String value) {
            addCriterion("cookie_id >=", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdLessThan(String value) {
            addCriterion("cookie_id <", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdLessThanOrEqualTo(String value) {
            addCriterion("cookie_id <=", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdLike(String value) {
            addCriterion("cookie_id like", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdNotLike(String value) {
            addCriterion("cookie_id not like", value, "cookieId");
            return this;
        }

        public Criteria andCookieIdIn(List values) {
            addCriterion("cookie_id in", values, "cookieId");
            return this;
        }

        public Criteria andCookieIdNotIn(List values) {
            addCriterion("cookie_id not in", values, "cookieId");
            return this;
        }

        public Criteria andCookieIdBetween(String value1, String value2) {
            addCriterion("cookie_id between", value1, value2, "cookieId");
            return this;
        }

        public Criteria andCookieIdNotBetween(String value1, String value2) {
            addCriterion("cookie_id not between", value1, value2, "cookieId");
            return this;
        }

        public Criteria andUserOprateUriIsNull() {
            addCriterion("user_oprate_uri is null");
            return this;
        }

        public Criteria andUserOprateUriIsNotNull() {
            addCriterion("user_oprate_uri is not null");
            return this;
        }

        public Criteria andUserOprateUriEqualTo(String value) {
            addCriterion("user_oprate_uri =", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriNotEqualTo(String value) {
            addCriterion("user_oprate_uri <>", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriGreaterThan(String value) {
            addCriterion("user_oprate_uri >", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriGreaterThanOrEqualTo(String value) {
            addCriterion("user_oprate_uri >=", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriLessThan(String value) {
            addCriterion("user_oprate_uri <", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriLessThanOrEqualTo(String value) {
            addCriterion("user_oprate_uri <=", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriLike(String value) {
            addCriterion("user_oprate_uri like", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriNotLike(String value) {
            addCriterion("user_oprate_uri not like", value, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriIn(List values) {
            addCriterion("user_oprate_uri in", values, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriNotIn(List values) {
            addCriterion("user_oprate_uri not in", values, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriBetween(String value1, String value2) {
            addCriterion("user_oprate_uri between", value1, value2, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateUriNotBetween(String value1, String value2) {
            addCriterion("user_oprate_uri not between", value1, value2, "userOprateUri");
            return this;
        }

        public Criteria andUserOprateParameIsNull() {
            addCriterion("user_oprate_parame is null");
            return this;
        }

        public Criteria andUserOprateParameIsNotNull() {
            addCriterion("user_oprate_parame is not null");
            return this;
        }

        public Criteria andUserOprateParameEqualTo(String value) {
            addCriterion("user_oprate_parame =", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameNotEqualTo(String value) {
            addCriterion("user_oprate_parame <>", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameGreaterThan(String value) {
            addCriterion("user_oprate_parame >", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameGreaterThanOrEqualTo(String value) {
            addCriterion("user_oprate_parame >=", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameLessThan(String value) {
            addCriterion("user_oprate_parame <", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameLessThanOrEqualTo(String value) {
            addCriterion("user_oprate_parame <=", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameLike(String value) {
            addCriterion("user_oprate_parame like", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameNotLike(String value) {
            addCriterion("user_oprate_parame not like", value, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameIn(List values) {
            addCriterion("user_oprate_parame in", values, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameNotIn(List values) {
            addCriterion("user_oprate_parame not in", values, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameBetween(String value1, String value2) {
            addCriterion("user_oprate_parame between", value1, value2, "userOprateParame");
            return this;
        }

        public Criteria andUserOprateParameNotBetween(String value1, String value2) {
            addCriterion("user_oprate_parame not between", value1, value2, "userOprateParame");
            return this;
        }

        public Criteria andUserLogTimeIsNull() {
            addCriterion("user_log_time is null");
            return this;
        }

        public Criteria andUserLogTimeIsNotNull() {
            addCriterion("user_log_time is not null");
            return this;
        }

        public Criteria andUserLogTimeEqualTo(Date value) {
            addCriterion("user_log_time =", value, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeNotEqualTo(Date value) {
            addCriterion("user_log_time <>", value, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeGreaterThan(Date value) {
            addCriterion("user_log_time >", value, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_log_time >=", value, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeLessThan(Date value) {
            addCriterion("user_log_time <", value, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_log_time <=", value, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeIn(List values) {
            addCriterion("user_log_time in", values, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeNotIn(List values) {
            addCriterion("user_log_time not in", values, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeBetween(Date value1, Date value2) {
            addCriterion("user_log_time between", value1, value2, "userLogTime");
            return this;
        }

        public Criteria andUserLogTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_log_time not between", value1, value2, "userLogTime");
            return this;
        }
    }
}