package app.cn.qtt.bm.model;

import java.util.Date;

public class TLogUserAccess {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_log_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer userLogId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String userCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_client_ip
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String userClientIp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_server_ip
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String userServerIp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_agent
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String userAgent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.session_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String sessionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.cookie_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String cookieId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_oprate_uri
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String userOprateUri;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_oprate_parame
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String userOprateParame;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_log_user_access.user_log_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date userLogTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_log_id
     *
     * @return the value of t_log_user_access.user_log_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getUserLogId() {
        return userLogId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_log_id
     *
     * @param userLogId the value for t_log_user_access.user_log_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserLogId(Integer userLogId) {
        this.userLogId = userLogId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_code
     *
     * @return the value of t_log_user_access.user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_code
     *
     * @param userCode the value for t_log_user_access.user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_client_ip
     *
     * @return the value of t_log_user_access.user_client_ip
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getUserClientIp() {
        return userClientIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_client_ip
     *
     * @param userClientIp the value for t_log_user_access.user_client_ip
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserClientIp(String userClientIp) {
        this.userClientIp = userClientIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_server_ip
     *
     * @return the value of t_log_user_access.user_server_ip
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getUserServerIp() {
        return userServerIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_server_ip
     *
     * @param userServerIp the value for t_log_user_access.user_server_ip
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserServerIp(String userServerIp) {
        this.userServerIp = userServerIp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_agent
     *
     * @return the value of t_log_user_access.user_agent
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_agent
     *
     * @param userAgent the value for t_log_user_access.user_agent
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.session_id
     *
     * @return the value of t_log_user_access.session_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.session_id
     *
     * @param sessionId the value for t_log_user_access.session_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.cookie_id
     *
     * @return the value of t_log_user_access.cookie_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCookieId() {
        return cookieId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.cookie_id
     *
     * @param cookieId the value for t_log_user_access.cookie_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCookieId(String cookieId) {
        this.cookieId = cookieId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_oprate_uri
     *
     * @return the value of t_log_user_access.user_oprate_uri
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getUserOprateUri() {
        return userOprateUri;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_oprate_uri
     *
     * @param userOprateUri the value for t_log_user_access.user_oprate_uri
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserOprateUri(String userOprateUri) {
        this.userOprateUri = userOprateUri;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_oprate_parame
     *
     * @return the value of t_log_user_access.user_oprate_parame
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getUserOprateParame() {
        return userOprateParame;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_oprate_parame
     *
     * @param userOprateParame the value for t_log_user_access.user_oprate_parame
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserOprateParame(String userOprateParame) {
        this.userOprateParame = userOprateParame;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_log_user_access.user_log_time
     *
     * @return the value of t_log_user_access.user_log_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getUserLogTime() {
        return userLogTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_log_user_access.user_log_time
     *
     * @param userLogTime the value for t_log_user_access.user_log_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setUserLogTime(Date userLogTime) {
        this.userLogTime = userLogTime;
    }
}