package app.cn.qtt.bm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TOrderInfoGoodsExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TOrderInfoGoodsExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected TOrderInfoGoodsExample(TOrderInfoGoodsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_order_info_goods
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andOrderGoodsIdIsNull() {
            addCriterion("order_goods_id is null");
            return this;
        }

        public Criteria andOrderGoodsIdIsNotNull() {
            addCriterion("order_goods_id is not null");
            return this;
        }

        public Criteria andOrderGoodsIdEqualTo(Integer value) {
            addCriterion("order_goods_id =", value, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdNotEqualTo(Integer value) {
            addCriterion("order_goods_id <>", value, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdGreaterThan(Integer value) {
            addCriterion("order_goods_id >", value, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_goods_id >=", value, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdLessThan(Integer value) {
            addCriterion("order_goods_id <", value, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_goods_id <=", value, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdIn(List values) {
            addCriterion("order_goods_id in", values, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdNotIn(List values) {
            addCriterion("order_goods_id not in", values, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("order_goods_id between", value1, value2, "orderGoodsId");
            return this;
        }

        public Criteria andOrderGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_goods_id not between", value1, value2, "orderGoodsId");
            return this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return this;
        }

        public Criteria andOrderIdIn(List values) {
            addCriterion("order_id in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdNotIn(List values) {
            addCriterion("order_id not in", values, "orderId");
            return this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return this;
        }

        public Criteria andShopGoodsIdIsNull() {
            addCriterion("shop_goods_id is null");
            return this;
        }

        public Criteria andShopGoodsIdIsNotNull() {
            addCriterion("shop_goods_id is not null");
            return this;
        }

        public Criteria andShopGoodsIdEqualTo(Integer value) {
            addCriterion("shop_goods_id =", value, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdNotEqualTo(Integer value) {
            addCriterion("shop_goods_id <>", value, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdGreaterThan(Integer value) {
            addCriterion("shop_goods_id >", value, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_goods_id >=", value, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdLessThan(Integer value) {
            addCriterion("shop_goods_id <", value, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_goods_id <=", value, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdIn(List values) {
            addCriterion("shop_goods_id in", values, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdNotIn(List values) {
            addCriterion("shop_goods_id not in", values, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_goods_id between", value1, value2, "shopGoodsId");
            return this;
        }

        public Criteria andShopGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_goods_id not between", value1, value2, "shopGoodsId");
            return this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return this;
        }

        public Criteria andShopIdIn(List values) {
            addCriterion("shop_id in", values, "shopId");
            return this;
        }

        public Criteria andShopIdNotIn(List values) {
            addCriterion("shop_id not in", values, "shopId");
            return this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return this;
        }

        public Criteria andShopGoodsCountIsNull() {
            addCriterion("shop_goods_count is null");
            return this;
        }

        public Criteria andShopGoodsCountIsNotNull() {
            addCriterion("shop_goods_count is not null");
            return this;
        }

        public Criteria andShopGoodsCountEqualTo(String value) {
            addCriterion("shop_goods_count =", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountNotEqualTo(String value) {
            addCriterion("shop_goods_count <>", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountGreaterThan(String value) {
            addCriterion("shop_goods_count >", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountGreaterThanOrEqualTo(String value) {
            addCriterion("shop_goods_count >=", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountLessThan(String value) {
            addCriterion("shop_goods_count <", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountLessThanOrEqualTo(String value) {
            addCriterion("shop_goods_count <=", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountLike(String value) {
            addCriterion("shop_goods_count like", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountNotLike(String value) {
            addCriterion("shop_goods_count not like", value, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountIn(List values) {
            addCriterion("shop_goods_count in", values, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountNotIn(List values) {
            addCriterion("shop_goods_count not in", values, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountBetween(String value1, String value2) {
            addCriterion("shop_goods_count between", value1, value2, "shopGoodsCount");
            return this;
        }

        public Criteria andShopGoodsCountNotBetween(String value1, String value2) {
            addCriterion("shop_goods_count not between", value1, value2, "shopGoodsCount");
            return this;
        }

        public Criteria andOrderGoodsSortIsNull() {
            addCriterion("order_goods_sort is null");
            return this;
        }

        public Criteria andOrderGoodsSortIsNotNull() {
            addCriterion("order_goods_sort is not null");
            return this;
        }

        public Criteria andOrderGoodsSortEqualTo(String value) {
            addCriterion("order_goods_sort =", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortNotEqualTo(String value) {
            addCriterion("order_goods_sort <>", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortGreaterThan(String value) {
            addCriterion("order_goods_sort >", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortGreaterThanOrEqualTo(String value) {
            addCriterion("order_goods_sort >=", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortLessThan(String value) {
            addCriterion("order_goods_sort <", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortLessThanOrEqualTo(String value) {
            addCriterion("order_goods_sort <=", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortLike(String value) {
            addCriterion("order_goods_sort like", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortNotLike(String value) {
            addCriterion("order_goods_sort not like", value, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortIn(List values) {
            addCriterion("order_goods_sort in", values, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortNotIn(List values) {
            addCriterion("order_goods_sort not in", values, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortBetween(String value1, String value2) {
            addCriterion("order_goods_sort between", value1, value2, "orderGoodsSort");
            return this;
        }

        public Criteria andOrderGoodsSortNotBetween(String value1, String value2) {
            addCriterion("order_goods_sort not between", value1, value2, "orderGoodsSort");
            return this;
        }

        public Criteria andCreateUserCodeIsNull() {
            addCriterion("create_user_code is null");
            return this;
        }

        public Criteria andCreateUserCodeIsNotNull() {
            addCriterion("create_user_code is not null");
            return this;
        }

        public Criteria andCreateUserCodeEqualTo(String value) {
            addCriterion("create_user_code =", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotEqualTo(String value) {
            addCriterion("create_user_code <>", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeGreaterThan(String value) {
            addCriterion("create_user_code >", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_code >=", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLessThan(String value) {
            addCriterion("create_user_code <", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLessThanOrEqualTo(String value) {
            addCriterion("create_user_code <=", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLike(String value) {
            addCriterion("create_user_code like", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotLike(String value) {
            addCriterion("create_user_code not like", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeIn(List values) {
            addCriterion("create_user_code in", values, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotIn(List values) {
            addCriterion("create_user_code not in", values, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeBetween(String value1, String value2) {
            addCriterion("create_user_code between", value1, value2, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotBetween(String value1, String value2) {
            addCriterion("create_user_code not between", value1, value2, "createUserCode");
            return this;
        }

        public Criteria andModifyUserCodeIsNull() {
            addCriterion("modify_user_code is null");
            return this;
        }

        public Criteria andModifyUserCodeIsNotNull() {
            addCriterion("modify_user_code is not null");
            return this;
        }

        public Criteria andModifyUserCodeEqualTo(String value) {
            addCriterion("modify_user_code =", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotEqualTo(String value) {
            addCriterion("modify_user_code <>", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeGreaterThan(String value) {
            addCriterion("modify_user_code >", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user_code >=", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLessThan(String value) {
            addCriterion("modify_user_code <", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLessThanOrEqualTo(String value) {
            addCriterion("modify_user_code <=", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLike(String value) {
            addCriterion("modify_user_code like", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotLike(String value) {
            addCriterion("modify_user_code not like", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeIn(List values) {
            addCriterion("modify_user_code in", values, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotIn(List values) {
            addCriterion("modify_user_code not in", values, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeBetween(String value1, String value2) {
            addCriterion("modify_user_code between", value1, value2, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotBetween(String value1, String value2) {
            addCriterion("modify_user_code not between", value1, value2, "modifyUserCode");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeIn(List values) {
            addCriterion("modify_time in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotIn(List values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return this;
        }
    }
}