package app.cn.qtt.bm.model;

import java.util.Date;

public class TOrderInfoGoods {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.order_goods_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer orderGoodsId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.order_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer orderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.shop_goods_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer shopGoodsId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer shopId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.shop_goods_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String shopGoodsCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.order_goods_sort
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String orderGoodsSort;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String createUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String modifyUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_order_info_goods.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date modifyTime;
    
    /**
     * Added by GeYanmeng 2013-6-17
     * 商品信息对象
     */
    private TShopGoods shopGoods;
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.order_goods_id
     *
     * @return the value of t_order_info_goods.order_goods_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.order_goods_id
     *
     * @param orderGoodsId the value for t_order_info_goods.order_goods_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setOrderGoodsId(Integer orderGoodsId) {
        this.orderGoodsId = orderGoodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.order_id
     *
     * @return the value of t_order_info_goods.order_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.order_id
     *
     * @param orderId the value for t_order_info_goods.order_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.shop_goods_id
     *
     * @return the value of t_order_info_goods.shop_goods_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getShopGoodsId() {
        return shopGoodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.shop_goods_id
     *
     * @param shopGoodsId the value for t_order_info_goods.shop_goods_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopGoodsId(Integer shopGoodsId) {
        this.shopGoodsId = shopGoodsId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.shop_id
     *
     * @return the value of t_order_info_goods.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.shop_id
     *
     * @param shopId the value for t_order_info_goods.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.shop_goods_count
     *
     * @return the value of t_order_info_goods.shop_goods_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getShopGoodsCount() {
        return shopGoodsCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.shop_goods_count
     *
     * @param shopGoodsCount the value for t_order_info_goods.shop_goods_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopGoodsCount(String shopGoodsCount) {
        this.shopGoodsCount = shopGoodsCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.order_goods_sort
     *
     * @return the value of t_order_info_goods.order_goods_sort
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getOrderGoodsSort() {
        return orderGoodsSort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.order_goods_sort
     *
     * @param orderGoodsSort the value for t_order_info_goods.order_goods_sort
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setOrderGoodsSort(String orderGoodsSort) {
        this.orderGoodsSort = orderGoodsSort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.create_user_code
     *
     * @return the value of t_order_info_goods.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.create_user_code
     *
     * @param createUserCode the value for t_order_info_goods.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.modify_user_code
     *
     * @return the value of t_order_info_goods.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getModifyUserCode() {
        return modifyUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.modify_user_code
     *
     * @param modifyUserCode the value for t_order_info_goods.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setModifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.create_time
     *
     * @return the value of t_order_info_goods.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.create_time
     *
     * @param createTime the value for t_order_info_goods.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_order_info_goods.modify_time
     *
     * @return the value of t_order_info_goods.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_order_info_goods.modify_time
     *
     * @param modifyTime the value for t_order_info_goods.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	/**
	 * @return the shopGoods
	 */
	public TShopGoods getShopGoods() {
		return shopGoods;
	}

	/**
	 * @param shopGoods the shopGoods to set
	 */
	public void setShopGoods(TShopGoods shopGoods) {
		this.shopGoods = shopGoods;
	}

}