package app.cn.qtt.bm.model;

import java.util.Date;

public class TOrderInfoShop {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.order_shop_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private Integer orderShopId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.order_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private Integer orderId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.shop_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private Integer shopId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.order_shop_qrcode
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private String orderShopQrcode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.create_user_code
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private String createUserCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.modify_user_code
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private String modifyUserCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.create_time
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.modify_time
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private Date modifyTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.order_shop_run_status
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private String orderShopRunStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.price
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private String price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_order_info_shop.captchas
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	private String captchas;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.order_shop_id
	 * @return  the value of t_order_info_shop.order_shop_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public Integer getOrderShopId() {
		return orderShopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.order_shop_id
	 * @param orderShopId  the value for t_order_info_shop.order_shop_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setOrderShopId(Integer orderShopId) {
		this.orderShopId = orderShopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.order_id
	 * @return  the value of t_order_info_shop.order_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.order_id
	 * @param orderId  the value for t_order_info_shop.order_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.shop_id
	 * @return  the value of t_order_info_shop.shop_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public Integer getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.shop_id
	 * @param shopId  the value for t_order_info_shop.shop_id
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.order_shop_qrcode
	 * @return  the value of t_order_info_shop.order_shop_qrcode
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public String getOrderShopQrcode() {
		return orderShopQrcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.order_shop_qrcode
	 * @param orderShopQrcode  the value for t_order_info_shop.order_shop_qrcode
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setOrderShopQrcode(String orderShopQrcode) {
		this.orderShopQrcode = orderShopQrcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.create_user_code
	 * @return  the value of t_order_info_shop.create_user_code
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public String getCreateUserCode() {
		return createUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.create_user_code
	 * @param createUserCode  the value for t_order_info_shop.create_user_code
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setCreateUserCode(String createUserCode) {
		this.createUserCode = createUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.modify_user_code
	 * @return  the value of t_order_info_shop.modify_user_code
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public String getModifyUserCode() {
		return modifyUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.modify_user_code
	 * @param modifyUserCode  the value for t_order_info_shop.modify_user_code
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setModifyUserCode(String modifyUserCode) {
		this.modifyUserCode = modifyUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.create_time
	 * @return  the value of t_order_info_shop.create_time
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.create_time
	 * @param createTime  the value for t_order_info_shop.create_time
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.modify_time
	 * @return  the value of t_order_info_shop.modify_time
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.modify_time
	 * @param modifyTime  the value for t_order_info_shop.modify_time
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.order_shop_run_status
	 * @return  the value of t_order_info_shop.order_shop_run_status
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public String getOrderShopRunStatus() {
		return orderShopRunStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.order_shop_run_status
	 * @param orderShopRunStatus  the value for t_order_info_shop.order_shop_run_status
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setOrderShopRunStatus(String orderShopRunStatus) {
		this.orderShopRunStatus = orderShopRunStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.price
	 * @return  the value of t_order_info_shop.price
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.price
	 * @param price  the value for t_order_info_shop.price
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_order_info_shop.captchas
	 * @return  the value of t_order_info_shop.captchas
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public String getCaptchas() {
		return captchas;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_order_info_shop.captchas
	 * @param captchas  the value for t_order_info_shop.captchas
	 * @abatorgenerated  Tue Sep 17 11:21:55 CST 2013
	 */
	public void setCaptchas(String captchas) {
		this.captchas = captchas;
	}

	/**
     * Added by GeYanmeng 2013-6-17
     * ??????
     */
    private TShopInfo shopInfo;

	/**
	 * @return the shopInfo
	 */
	public TShopInfo getShopInfo() {
		return shopInfo;
	}

	/**
	 * @param shopInfo the shopInfo to set
	 */
	public void setShopInfo(TShopInfo shopInfo) {
		this.shopInfo = shopInfo;
	}
}