package app.cn.qtt.bm.model;

import java.util.Date;

public class TSendMmsHistory {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer mmsHistoryId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_fegin_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsFeginCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_send_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistorySendMdn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_receive_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistoryReceiveMdn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_subject
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistorySubject;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistorySn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_send_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistorySendStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_send_swift
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistorySendSwift;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_fee_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistoryFeeType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date mmsHistoryCreateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date mmsHistoryModifyTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_send_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistorySendType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_send_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer mmsHistorySendCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_transparent_number
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistoryTransparentNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_before_send_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date mmsHistoryBeforeSendTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_after_send_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date mmsHistoryAfterSendTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_mms_history.mms_history_file_paths
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String mmsHistoryFilePaths;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_id
     *
     * @return the value of t_send_mms_history.mms_history_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getMmsHistoryId() {
        return mmsHistoryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_id
     *
     * @param mmsHistoryId the value for t_send_mms_history.mms_history_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryId(Integer mmsHistoryId) {
        this.mmsHistoryId = mmsHistoryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_fegin_code
     *
     * @return the value of t_send_mms_history.mms_fegin_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsFeginCode() {
        return mmsFeginCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_fegin_code
     *
     * @param mmsFeginCode the value for t_send_mms_history.mms_fegin_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsFeginCode(String mmsFeginCode) {
        this.mmsFeginCode = mmsFeginCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_send_mdn
     *
     * @return the value of t_send_mms_history.mms_history_send_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistorySendMdn() {
        return mmsHistorySendMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_send_mdn
     *
     * @param mmsHistorySendMdn the value for t_send_mms_history.mms_history_send_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySendMdn(String mmsHistorySendMdn) {
        this.mmsHistorySendMdn = mmsHistorySendMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_receive_mdn
     *
     * @return the value of t_send_mms_history.mms_history_receive_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistoryReceiveMdn() {
        return mmsHistoryReceiveMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_receive_mdn
     *
     * @param mmsHistoryReceiveMdn the value for t_send_mms_history.mms_history_receive_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryReceiveMdn(String mmsHistoryReceiveMdn) {
        this.mmsHistoryReceiveMdn = mmsHistoryReceiveMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_subject
     *
     * @return the value of t_send_mms_history.mms_history_subject
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistorySubject() {
        return mmsHistorySubject;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_subject
     *
     * @param mmsHistorySubject the value for t_send_mms_history.mms_history_subject
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySubject(String mmsHistorySubject) {
        this.mmsHistorySubject = mmsHistorySubject;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_sn
     *
     * @return the value of t_send_mms_history.mms_history_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistorySn() {
        return mmsHistorySn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_sn
     *
     * @param mmsHistorySn the value for t_send_mms_history.mms_history_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySn(String mmsHistorySn) {
        this.mmsHistorySn = mmsHistorySn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_send_status
     *
     * @return the value of t_send_mms_history.mms_history_send_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistorySendStatus() {
        return mmsHistorySendStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_send_status
     *
     * @param mmsHistorySendStatus the value for t_send_mms_history.mms_history_send_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySendStatus(String mmsHistorySendStatus) {
        this.mmsHistorySendStatus = mmsHistorySendStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_send_swift
     *
     * @return the value of t_send_mms_history.mms_history_send_swift
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistorySendSwift() {
        return mmsHistorySendSwift;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_send_swift
     *
     * @param mmsHistorySendSwift the value for t_send_mms_history.mms_history_send_swift
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySendSwift(String mmsHistorySendSwift) {
        this.mmsHistorySendSwift = mmsHistorySendSwift;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_fee_type
     *
     * @return the value of t_send_mms_history.mms_history_fee_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistoryFeeType() {
        return mmsHistoryFeeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_fee_type
     *
     * @param mmsHistoryFeeType the value for t_send_mms_history.mms_history_fee_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryFeeType(String mmsHistoryFeeType) {
        this.mmsHistoryFeeType = mmsHistoryFeeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_create_time
     *
     * @return the value of t_send_mms_history.mms_history_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getMmsHistoryCreateTime() {
        return mmsHistoryCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_create_time
     *
     * @param mmsHistoryCreateTime the value for t_send_mms_history.mms_history_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryCreateTime(Date mmsHistoryCreateTime) {
        this.mmsHistoryCreateTime = mmsHistoryCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_modify_time
     *
     * @return the value of t_send_mms_history.mms_history_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getMmsHistoryModifyTime() {
        return mmsHistoryModifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_modify_time
     *
     * @param mmsHistoryModifyTime the value for t_send_mms_history.mms_history_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryModifyTime(Date mmsHistoryModifyTime) {
        this.mmsHistoryModifyTime = mmsHistoryModifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_send_type
     *
     * @return the value of t_send_mms_history.mms_history_send_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistorySendType() {
        return mmsHistorySendType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_send_type
     *
     * @param mmsHistorySendType the value for t_send_mms_history.mms_history_send_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySendType(String mmsHistorySendType) {
        this.mmsHistorySendType = mmsHistorySendType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_send_count
     *
     * @return the value of t_send_mms_history.mms_history_send_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getMmsHistorySendCount() {
        return mmsHistorySendCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_send_count
     *
     * @param mmsHistorySendCount the value for t_send_mms_history.mms_history_send_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistorySendCount(Integer mmsHistorySendCount) {
        this.mmsHistorySendCount = mmsHistorySendCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_transparent_number
     *
     * @return the value of t_send_mms_history.mms_history_transparent_number
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistoryTransparentNumber() {
        return mmsHistoryTransparentNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_transparent_number
     *
     * @param mmsHistoryTransparentNumber the value for t_send_mms_history.mms_history_transparent_number
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryTransparentNumber(String mmsHistoryTransparentNumber) {
        this.mmsHistoryTransparentNumber = mmsHistoryTransparentNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_before_send_time
     *
     * @return the value of t_send_mms_history.mms_history_before_send_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getMmsHistoryBeforeSendTime() {
        return mmsHistoryBeforeSendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_before_send_time
     *
     * @param mmsHistoryBeforeSendTime the value for t_send_mms_history.mms_history_before_send_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryBeforeSendTime(Date mmsHistoryBeforeSendTime) {
        this.mmsHistoryBeforeSendTime = mmsHistoryBeforeSendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_after_send_time
     *
     * @return the value of t_send_mms_history.mms_history_after_send_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getMmsHistoryAfterSendTime() {
        return mmsHistoryAfterSendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_after_send_time
     *
     * @param mmsHistoryAfterSendTime the value for t_send_mms_history.mms_history_after_send_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryAfterSendTime(Date mmsHistoryAfterSendTime) {
        this.mmsHistoryAfterSendTime = mmsHistoryAfterSendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_mms_history.mms_history_file_paths
     *
     * @return the value of t_send_mms_history.mms_history_file_paths
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getMmsHistoryFilePaths() {
        return mmsHistoryFilePaths;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_mms_history.mms_history_file_paths
     *
     * @param mmsHistoryFilePaths the value for t_send_mms_history.mms_history_file_paths
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setMmsHistoryFilePaths(String mmsHistoryFilePaths) {
        this.mmsHistoryFilePaths = mmsHistoryFilePaths;
    }
}