package app.cn.qtt.bm.model;

import java.util.Date;

public class TSendSmsHistory {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Long historyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_buffer_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyBufferSn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sms_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySmsSn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_fa_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyFaStr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_oa_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyOaStr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sp_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySpId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sp_password
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySpPassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sp_service_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySpServiceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_token_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyTokenStr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sender_name
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySenderName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_message
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyMessage;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_receiver_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyReceiverMdn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_source_addr
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historySourceAddr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_sms_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date historySmsCreateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_send_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer historySendCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date historyCreateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date historyModifyTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer historyStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_send_sms_history.history_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String historyType;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_id
     *
     * @return the value of t_send_sms_history.history_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Long getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_id
     *
     * @param historyId the value for t_send_sms_history.history_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_buffer_sn
     *
     * @return the value of t_send_sms_history.history_buffer_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryBufferSn() {
        return historyBufferSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_buffer_sn
     *
     * @param historyBufferSn the value for t_send_sms_history.history_buffer_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryBufferSn(String historyBufferSn) {
        this.historyBufferSn = historyBufferSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sn
     *
     * @return the value of t_send_sms_history.history_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySn() {
        return historySn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sn
     *
     * @param historySn the value for t_send_sms_history.history_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySn(String historySn) {
        this.historySn = historySn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sms_sn
     *
     * @return the value of t_send_sms_history.history_sms_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySmsSn() {
        return historySmsSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sms_sn
     *
     * @param historySmsSn the value for t_send_sms_history.history_sms_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySmsSn(String historySmsSn) {
        this.historySmsSn = historySmsSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_fa_str
     *
     * @return the value of t_send_sms_history.history_fa_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryFaStr() {
        return historyFaStr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_fa_str
     *
     * @param historyFaStr the value for t_send_sms_history.history_fa_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryFaStr(String historyFaStr) {
        this.historyFaStr = historyFaStr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_oa_str
     *
     * @return the value of t_send_sms_history.history_oa_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryOaStr() {
        return historyOaStr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_oa_str
     *
     * @param historyOaStr the value for t_send_sms_history.history_oa_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryOaStr(String historyOaStr) {
        this.historyOaStr = historyOaStr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sp_id
     *
     * @return the value of t_send_sms_history.history_sp_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySpId() {
        return historySpId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sp_id
     *
     * @param historySpId the value for t_send_sms_history.history_sp_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySpId(String historySpId) {
        this.historySpId = historySpId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sp_password
     *
     * @return the value of t_send_sms_history.history_sp_password
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySpPassword() {
        return historySpPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sp_password
     *
     * @param historySpPassword the value for t_send_sms_history.history_sp_password
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySpPassword(String historySpPassword) {
        this.historySpPassword = historySpPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sp_service_id
     *
     * @return the value of t_send_sms_history.history_sp_service_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySpServiceId() {
        return historySpServiceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sp_service_id
     *
     * @param historySpServiceId the value for t_send_sms_history.history_sp_service_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySpServiceId(String historySpServiceId) {
        this.historySpServiceId = historySpServiceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_token_str
     *
     * @return the value of t_send_sms_history.history_token_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryTokenStr() {
        return historyTokenStr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_token_str
     *
     * @param historyTokenStr the value for t_send_sms_history.history_token_str
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryTokenStr(String historyTokenStr) {
        this.historyTokenStr = historyTokenStr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sender_name
     *
     * @return the value of t_send_sms_history.history_sender_name
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySenderName() {
        return historySenderName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sender_name
     *
     * @param historySenderName the value for t_send_sms_history.history_sender_name
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySenderName(String historySenderName) {
        this.historySenderName = historySenderName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_message
     *
     * @return the value of t_send_sms_history.history_message
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryMessage() {
        return historyMessage;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_message
     *
     * @param historyMessage the value for t_send_sms_history.history_message
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryMessage(String historyMessage) {
        this.historyMessage = historyMessage;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_receiver_mdn
     *
     * @return the value of t_send_sms_history.history_receiver_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryReceiverMdn() {
        return historyReceiverMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_receiver_mdn
     *
     * @param historyReceiverMdn the value for t_send_sms_history.history_receiver_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryReceiverMdn(String historyReceiverMdn) {
        this.historyReceiverMdn = historyReceiverMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_source_addr
     *
     * @return the value of t_send_sms_history.history_source_addr
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistorySourceAddr() {
        return historySourceAddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_source_addr
     *
     * @param historySourceAddr the value for t_send_sms_history.history_source_addr
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySourceAddr(String historySourceAddr) {
        this.historySourceAddr = historySourceAddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_sms_create_time
     *
     * @return the value of t_send_sms_history.history_sms_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getHistorySmsCreateTime() {
        return historySmsCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_sms_create_time
     *
     * @param historySmsCreateTime the value for t_send_sms_history.history_sms_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySmsCreateTime(Date historySmsCreateTime) {
        this.historySmsCreateTime = historySmsCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_send_count
     *
     * @return the value of t_send_sms_history.history_send_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getHistorySendCount() {
        return historySendCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_send_count
     *
     * @param historySendCount the value for t_send_sms_history.history_send_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistorySendCount(Integer historySendCount) {
        this.historySendCount = historySendCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_create_time
     *
     * @return the value of t_send_sms_history.history_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getHistoryCreateTime() {
        return historyCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_create_time
     *
     * @param historyCreateTime the value for t_send_sms_history.history_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryCreateTime(Date historyCreateTime) {
        this.historyCreateTime = historyCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_modify_time
     *
     * @return the value of t_send_sms_history.history_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getHistoryModifyTime() {
        return historyModifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_modify_time
     *
     * @param historyModifyTime the value for t_send_sms_history.history_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryModifyTime(Date historyModifyTime) {
        this.historyModifyTime = historyModifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_status
     *
     * @return the value of t_send_sms_history.history_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getHistoryStatus() {
        return historyStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_status
     *
     * @param historyStatus the value for t_send_sms_history.history_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryStatus(Integer historyStatus) {
        this.historyStatus = historyStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_send_sms_history.history_type
     *
     * @return the value of t_send_sms_history.history_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getHistoryType() {
        return historyType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_send_sms_history.history_type
     *
     * @param historyType the value for t_send_sms_history.history_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setHistoryType(String historyType) {
        this.historyType = historyType;
    }
}