package app.cn.qtt.bm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSendEmailHistoryExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public TSendEmailHistoryExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    protected TSendEmailHistoryExample(TSendEmailHistoryExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_send_email_history
     *
     * @abatorgenerated Fri Jun 21 11:12:52 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andHistoryEmailIdIsNull() {
            addCriterion("history_email_id is null");
            return this;
        }

        public Criteria andHistoryEmailIdIsNotNull() {
            addCriterion("history_email_id is not null");
            return this;
        }

        public Criteria andHistoryEmailIdEqualTo(Integer value) {
            addCriterion("history_email_id =", value, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdNotEqualTo(Integer value) {
            addCriterion("history_email_id <>", value, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdGreaterThan(Integer value) {
            addCriterion("history_email_id >", value, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("history_email_id >=", value, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdLessThan(Integer value) {
            addCriterion("history_email_id <", value, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdLessThanOrEqualTo(Integer value) {
            addCriterion("history_email_id <=", value, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdIn(List values) {
            addCriterion("history_email_id in", values, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdNotIn(List values) {
            addCriterion("history_email_id not in", values, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdBetween(Integer value1, Integer value2) {
            addCriterion("history_email_id between", value1, value2, "historyEmailId");
            return this;
        }

        public Criteria andHistoryEmailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("history_email_id not between", value1, value2, "historyEmailId");
            return this;
        }

        public Criteria andBufferEmailCodeIsNull() {
            addCriterion("buffer_email_code is null");
            return this;
        }

        public Criteria andBufferEmailCodeIsNotNull() {
            addCriterion("buffer_email_code is not null");
            return this;
        }

        public Criteria andBufferEmailCodeEqualTo(String value) {
            addCriterion("buffer_email_code =", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeNotEqualTo(String value) {
            addCriterion("buffer_email_code <>", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeGreaterThan(String value) {
            addCriterion("buffer_email_code >", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeGreaterThanOrEqualTo(String value) {
            addCriterion("buffer_email_code >=", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeLessThan(String value) {
            addCriterion("buffer_email_code <", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeLessThanOrEqualTo(String value) {
            addCriterion("buffer_email_code <=", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeLike(String value) {
            addCriterion("buffer_email_code like", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeNotLike(String value) {
            addCriterion("buffer_email_code not like", value, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeIn(List values) {
            addCriterion("buffer_email_code in", values, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeNotIn(List values) {
            addCriterion("buffer_email_code not in", values, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeBetween(String value1, String value2) {
            addCriterion("buffer_email_code between", value1, value2, "bufferEmailCode");
            return this;
        }

        public Criteria andBufferEmailCodeNotBetween(String value1, String value2) {
            addCriterion("buffer_email_code not between", value1, value2, "bufferEmailCode");
            return this;
        }

        public Criteria andHistoryEmailToAddressIsNull() {
            addCriterion("history_email_to_address is null");
            return this;
        }

        public Criteria andHistoryEmailToAddressIsNotNull() {
            addCriterion("history_email_to_address is not null");
            return this;
        }

        public Criteria andHistoryEmailToAddressEqualTo(String value) {
            addCriterion("history_email_to_address =", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressNotEqualTo(String value) {
            addCriterion("history_email_to_address <>", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressGreaterThan(String value) {
            addCriterion("history_email_to_address >", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_to_address >=", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressLessThan(String value) {
            addCriterion("history_email_to_address <", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressLessThanOrEqualTo(String value) {
            addCriterion("history_email_to_address <=", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressLike(String value) {
            addCriterion("history_email_to_address like", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressNotLike(String value) {
            addCriterion("history_email_to_address not like", value, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressIn(List values) {
            addCriterion("history_email_to_address in", values, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressNotIn(List values) {
            addCriterion("history_email_to_address not in", values, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressBetween(String value1, String value2) {
            addCriterion("history_email_to_address between", value1, value2, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailToAddressNotBetween(String value1, String value2) {
            addCriterion("history_email_to_address not between", value1, value2, "historyEmailToAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressIsNull() {
            addCriterion("history_email_from_address is null");
            return this;
        }

        public Criteria andHistoryEmailFromAddressIsNotNull() {
            addCriterion("history_email_from_address is not null");
            return this;
        }

        public Criteria andHistoryEmailFromAddressEqualTo(String value) {
            addCriterion("history_email_from_address =", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressNotEqualTo(String value) {
            addCriterion("history_email_from_address <>", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressGreaterThan(String value) {
            addCriterion("history_email_from_address >", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_from_address >=", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressLessThan(String value) {
            addCriterion("history_email_from_address <", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressLessThanOrEqualTo(String value) {
            addCriterion("history_email_from_address <=", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressLike(String value) {
            addCriterion("history_email_from_address like", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressNotLike(String value) {
            addCriterion("history_email_from_address not like", value, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressIn(List values) {
            addCriterion("history_email_from_address in", values, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressNotIn(List values) {
            addCriterion("history_email_from_address not in", values, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressBetween(String value1, String value2) {
            addCriterion("history_email_from_address between", value1, value2, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailFromAddressNotBetween(String value1, String value2) {
            addCriterion("history_email_from_address not between", value1, value2, "historyEmailFromAddress");
            return this;
        }

        public Criteria andHistoryEmailValidateIsNull() {
            addCriterion("history_email_validate is null");
            return this;
        }

        public Criteria andHistoryEmailValidateIsNotNull() {
            addCriterion("history_email_validate is not null");
            return this;
        }

        public Criteria andHistoryEmailValidateEqualTo(String value) {
            addCriterion("history_email_validate =", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateNotEqualTo(String value) {
            addCriterion("history_email_validate <>", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateGreaterThan(String value) {
            addCriterion("history_email_validate >", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_validate >=", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateLessThan(String value) {
            addCriterion("history_email_validate <", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateLessThanOrEqualTo(String value) {
            addCriterion("history_email_validate <=", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateLike(String value) {
            addCriterion("history_email_validate like", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateNotLike(String value) {
            addCriterion("history_email_validate not like", value, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateIn(List values) {
            addCriterion("history_email_validate in", values, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateNotIn(List values) {
            addCriterion("history_email_validate not in", values, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateBetween(String value1, String value2) {
            addCriterion("history_email_validate between", value1, value2, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailValidateNotBetween(String value1, String value2) {
            addCriterion("history_email_validate not between", value1, value2, "historyEmailValidate");
            return this;
        }

        public Criteria andHistoryEmailUserNameIsNull() {
            addCriterion("history_email_user_name is null");
            return this;
        }

        public Criteria andHistoryEmailUserNameIsNotNull() {
            addCriterion("history_email_user_name is not null");
            return this;
        }

        public Criteria andHistoryEmailUserNameEqualTo(String value) {
            addCriterion("history_email_user_name =", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameNotEqualTo(String value) {
            addCriterion("history_email_user_name <>", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameGreaterThan(String value) {
            addCriterion("history_email_user_name >", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_user_name >=", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameLessThan(String value) {
            addCriterion("history_email_user_name <", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameLessThanOrEqualTo(String value) {
            addCriterion("history_email_user_name <=", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameLike(String value) {
            addCriterion("history_email_user_name like", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameNotLike(String value) {
            addCriterion("history_email_user_name not like", value, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameIn(List values) {
            addCriterion("history_email_user_name in", values, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameNotIn(List values) {
            addCriterion("history_email_user_name not in", values, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameBetween(String value1, String value2) {
            addCriterion("history_email_user_name between", value1, value2, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailUserNameNotBetween(String value1, String value2) {
            addCriterion("history_email_user_name not between", value1, value2, "historyEmailUserName");
            return this;
        }

        public Criteria andHistoryEmailPasswordIsNull() {
            addCriterion("history_email_password is null");
            return this;
        }

        public Criteria andHistoryEmailPasswordIsNotNull() {
            addCriterion("history_email_password is not null");
            return this;
        }

        public Criteria andHistoryEmailPasswordEqualTo(String value) {
            addCriterion("history_email_password =", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordNotEqualTo(String value) {
            addCriterion("history_email_password <>", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordGreaterThan(String value) {
            addCriterion("history_email_password >", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_password >=", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordLessThan(String value) {
            addCriterion("history_email_password <", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordLessThanOrEqualTo(String value) {
            addCriterion("history_email_password <=", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordLike(String value) {
            addCriterion("history_email_password like", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordNotLike(String value) {
            addCriterion("history_email_password not like", value, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordIn(List values) {
            addCriterion("history_email_password in", values, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordNotIn(List values) {
            addCriterion("history_email_password not in", values, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordBetween(String value1, String value2) {
            addCriterion("history_email_password between", value1, value2, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailPasswordNotBetween(String value1, String value2) {
            addCriterion("history_email_password not between", value1, value2, "historyEmailPassword");
            return this;
        }

        public Criteria andHistoryEmailSubjectIsNull() {
            addCriterion("history_email_subject is null");
            return this;
        }

        public Criteria andHistoryEmailSubjectIsNotNull() {
            addCriterion("history_email_subject is not null");
            return this;
        }

        public Criteria andHistoryEmailSubjectEqualTo(String value) {
            addCriterion("history_email_subject =", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectNotEqualTo(String value) {
            addCriterion("history_email_subject <>", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectGreaterThan(String value) {
            addCriterion("history_email_subject >", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_subject >=", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectLessThan(String value) {
            addCriterion("history_email_subject <", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectLessThanOrEqualTo(String value) {
            addCriterion("history_email_subject <=", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectLike(String value) {
            addCriterion("history_email_subject like", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectNotLike(String value) {
            addCriterion("history_email_subject not like", value, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectIn(List values) {
            addCriterion("history_email_subject in", values, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectNotIn(List values) {
            addCriterion("history_email_subject not in", values, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectBetween(String value1, String value2) {
            addCriterion("history_email_subject between", value1, value2, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailSubjectNotBetween(String value1, String value2) {
            addCriterion("history_email_subject not between", value1, value2, "historyEmailSubject");
            return this;
        }

        public Criteria andHistoryEmailContentIsNull() {
            addCriterion("history_email_content is null");
            return this;
        }

        public Criteria andHistoryEmailContentIsNotNull() {
            addCriterion("history_email_content is not null");
            return this;
        }

        public Criteria andHistoryEmailContentEqualTo(String value) {
            addCriterion("history_email_content =", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentNotEqualTo(String value) {
            addCriterion("history_email_content <>", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentGreaterThan(String value) {
            addCriterion("history_email_content >", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_content >=", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentLessThan(String value) {
            addCriterion("history_email_content <", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentLessThanOrEqualTo(String value) {
            addCriterion("history_email_content <=", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentLike(String value) {
            addCriterion("history_email_content like", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentNotLike(String value) {
            addCriterion("history_email_content not like", value, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentIn(List values) {
            addCriterion("history_email_content in", values, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentNotIn(List values) {
            addCriterion("history_email_content not in", values, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentBetween(String value1, String value2) {
            addCriterion("history_email_content between", value1, value2, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailContentNotBetween(String value1, String value2) {
            addCriterion("history_email_content not between", value1, value2, "historyEmailContent");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesIsNull() {
            addCriterion("history_email_attach_files is null");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesIsNotNull() {
            addCriterion("history_email_attach_files is not null");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesEqualTo(String value) {
            addCriterion("history_email_attach_files =", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesNotEqualTo(String value) {
            addCriterion("history_email_attach_files <>", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesGreaterThan(String value) {
            addCriterion("history_email_attach_files >", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_attach_files >=", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesLessThan(String value) {
            addCriterion("history_email_attach_files <", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesLessThanOrEqualTo(String value) {
            addCriterion("history_email_attach_files <=", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesLike(String value) {
            addCriterion("history_email_attach_files like", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesNotLike(String value) {
            addCriterion("history_email_attach_files not like", value, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesIn(List values) {
            addCriterion("history_email_attach_files in", values, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesNotIn(List values) {
            addCriterion("history_email_attach_files not in", values, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesBetween(String value1, String value2) {
            addCriterion("history_email_attach_files between", value1, value2, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailAttachFilesNotBetween(String value1, String value2) {
            addCriterion("history_email_attach_files not between", value1, value2, "historyEmailAttachFiles");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostIsNull() {
            addCriterion("history_email_smtp_host is null");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostIsNotNull() {
            addCriterion("history_email_smtp_host is not null");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostEqualTo(String value) {
            addCriterion("history_email_smtp_host =", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostNotEqualTo(String value) {
            addCriterion("history_email_smtp_host <>", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostGreaterThan(String value) {
            addCriterion("history_email_smtp_host >", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_smtp_host >=", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostLessThan(String value) {
            addCriterion("history_email_smtp_host <", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostLessThanOrEqualTo(String value) {
            addCriterion("history_email_smtp_host <=", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostLike(String value) {
            addCriterion("history_email_smtp_host like", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostNotLike(String value) {
            addCriterion("history_email_smtp_host not like", value, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostIn(List values) {
            addCriterion("history_email_smtp_host in", values, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostNotIn(List values) {
            addCriterion("history_email_smtp_host not in", values, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostBetween(String value1, String value2) {
            addCriterion("history_email_smtp_host between", value1, value2, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpHostNotBetween(String value1, String value2) {
            addCriterion("history_email_smtp_host not between", value1, value2, "historyEmailSmtpHost");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortIsNull() {
            addCriterion("history_email_smtp_port is null");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortIsNotNull() {
            addCriterion("history_email_smtp_port is not null");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortEqualTo(String value) {
            addCriterion("history_email_smtp_port =", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortNotEqualTo(String value) {
            addCriterion("history_email_smtp_port <>", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortGreaterThan(String value) {
            addCriterion("history_email_smtp_port >", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_smtp_port >=", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortLessThan(String value) {
            addCriterion("history_email_smtp_port <", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortLessThanOrEqualTo(String value) {
            addCriterion("history_email_smtp_port <=", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortLike(String value) {
            addCriterion("history_email_smtp_port like", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortNotLike(String value) {
            addCriterion("history_email_smtp_port not like", value, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortIn(List values) {
            addCriterion("history_email_smtp_port in", values, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortNotIn(List values) {
            addCriterion("history_email_smtp_port not in", values, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortBetween(String value1, String value2) {
            addCriterion("history_email_smtp_port between", value1, value2, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailSmtpPortNotBetween(String value1, String value2) {
            addCriterion("history_email_smtp_port not between", value1, value2, "historyEmailSmtpPort");
            return this;
        }

        public Criteria andHistoryEmailStartusIsNull() {
            addCriterion("history_email_startus is null");
            return this;
        }

        public Criteria andHistoryEmailStartusIsNotNull() {
            addCriterion("history_email_startus is not null");
            return this;
        }

        public Criteria andHistoryEmailStartusEqualTo(String value) {
            addCriterion("history_email_startus =", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusNotEqualTo(String value) {
            addCriterion("history_email_startus <>", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusGreaterThan(String value) {
            addCriterion("history_email_startus >", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_startus >=", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusLessThan(String value) {
            addCriterion("history_email_startus <", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusLessThanOrEqualTo(String value) {
            addCriterion("history_email_startus <=", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusLike(String value) {
            addCriterion("history_email_startus like", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusNotLike(String value) {
            addCriterion("history_email_startus not like", value, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusIn(List values) {
            addCriterion("history_email_startus in", values, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusNotIn(List values) {
            addCriterion("history_email_startus not in", values, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusBetween(String value1, String value2) {
            addCriterion("history_email_startus between", value1, value2, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailStartusNotBetween(String value1, String value2) {
            addCriterion("history_email_startus not between", value1, value2, "historyEmailStartus");
            return this;
        }

        public Criteria andHistoryEmailTypeIsNull() {
            addCriterion("history_email_type is null");
            return this;
        }

        public Criteria andHistoryEmailTypeIsNotNull() {
            addCriterion("history_email_type is not null");
            return this;
        }

        public Criteria andHistoryEmailTypeEqualTo(String value) {
            addCriterion("history_email_type =", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeNotEqualTo(String value) {
            addCriterion("history_email_type <>", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeGreaterThan(String value) {
            addCriterion("history_email_type >", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeGreaterThanOrEqualTo(String value) {
            addCriterion("history_email_type >=", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeLessThan(String value) {
            addCriterion("history_email_type <", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeLessThanOrEqualTo(String value) {
            addCriterion("history_email_type <=", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeLike(String value) {
            addCriterion("history_email_type like", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeNotLike(String value) {
            addCriterion("history_email_type not like", value, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeIn(List values) {
            addCriterion("history_email_type in", values, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeNotIn(List values) {
            addCriterion("history_email_type not in", values, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeBetween(String value1, String value2) {
            addCriterion("history_email_type between", value1, value2, "historyEmailType");
            return this;
        }

        public Criteria andHistoryEmailTypeNotBetween(String value1, String value2) {
            addCriterion("history_email_type not between", value1, value2, "historyEmailType");
            return this;
        }

        public Criteria andCreateUserCodeIsNull() {
            addCriterion("create_user_code is null");
            return this;
        }

        public Criteria andCreateUserCodeIsNotNull() {
            addCriterion("create_user_code is not null");
            return this;
        }

        public Criteria andCreateUserCodeEqualTo(String value) {
            addCriterion("create_user_code =", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotEqualTo(String value) {
            addCriterion("create_user_code <>", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeGreaterThan(String value) {
            addCriterion("create_user_code >", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_code >=", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLessThan(String value) {
            addCriterion("create_user_code <", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLessThanOrEqualTo(String value) {
            addCriterion("create_user_code <=", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLike(String value) {
            addCriterion("create_user_code like", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotLike(String value) {
            addCriterion("create_user_code not like", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeIn(List values) {
            addCriterion("create_user_code in", values, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotIn(List values) {
            addCriterion("create_user_code not in", values, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeBetween(String value1, String value2) {
            addCriterion("create_user_code between", value1, value2, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotBetween(String value1, String value2) {
            addCriterion("create_user_code not between", value1, value2, "createUserCode");
            return this;
        }

        public Criteria andModifyUserCodeIsNull() {
            addCriterion("modify_user_code is null");
            return this;
        }

        public Criteria andModifyUserCodeIsNotNull() {
            addCriterion("modify_user_code is not null");
            return this;
        }

        public Criteria andModifyUserCodeEqualTo(String value) {
            addCriterion("modify_user_code =", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotEqualTo(String value) {
            addCriterion("modify_user_code <>", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeGreaterThan(String value) {
            addCriterion("modify_user_code >", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user_code >=", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLessThan(String value) {
            addCriterion("modify_user_code <", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLessThanOrEqualTo(String value) {
            addCriterion("modify_user_code <=", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLike(String value) {
            addCriterion("modify_user_code like", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotLike(String value) {
            addCriterion("modify_user_code not like", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeIn(List values) {
            addCriterion("modify_user_code in", values, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotIn(List values) {
            addCriterion("modify_user_code not in", values, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeBetween(String value1, String value2) {
            addCriterion("modify_user_code between", value1, value2, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotBetween(String value1, String value2) {
            addCriterion("modify_user_code not between", value1, value2, "modifyUserCode");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeIn(List values) {
            addCriterion("modify_time in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotIn(List values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return this;
        }
    }
}