package app.cn.qtt.bm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TShopInfoExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public TShopInfoExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected TShopInfoExample(TShopInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_shop_info
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return this;
        }

        public Criteria andShopIdIn(List values) {
            addCriterion("shop_id in", values, "shopId");
            return this;
        }

        public Criteria andShopIdNotIn(List values) {
            addCriterion("shop_id not in", values, "shopId");
            return this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return this;
        }

        public Criteria andShopNameIn(List values) {
            addCriterion("shop_name in", values, "shopName");
            return this;
        }

        public Criteria andShopNameNotIn(List values) {
            addCriterion("shop_name not in", values, "shopName");
            return this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return this;
        }

        public Criteria andShopDescIsNull() {
            addCriterion("shop_desc is null");
            return this;
        }

        public Criteria andShopDescIsNotNull() {
            addCriterion("shop_desc is not null");
            return this;
        }

        public Criteria andShopDescEqualTo(String value) {
            addCriterion("shop_desc =", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescNotEqualTo(String value) {
            addCriterion("shop_desc <>", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescGreaterThan(String value) {
            addCriterion("shop_desc >", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescGreaterThanOrEqualTo(String value) {
            addCriterion("shop_desc >=", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescLessThan(String value) {
            addCriterion("shop_desc <", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescLessThanOrEqualTo(String value) {
            addCriterion("shop_desc <=", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescLike(String value) {
            addCriterion("shop_desc like", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescNotLike(String value) {
            addCriterion("shop_desc not like", value, "shopDesc");
            return this;
        }

        public Criteria andShopDescIn(List values) {
            addCriterion("shop_desc in", values, "shopDesc");
            return this;
        }

        public Criteria andShopDescNotIn(List values) {
            addCriterion("shop_desc not in", values, "shopDesc");
            return this;
        }

        public Criteria andShopDescBetween(String value1, String value2) {
            addCriterion("shop_desc between", value1, value2, "shopDesc");
            return this;
        }

        public Criteria andShopDescNotBetween(String value1, String value2) {
            addCriterion("shop_desc not between", value1, value2, "shopDesc");
            return this;
        }

        public Criteria andShopAddressIsNull() {
            addCriterion("shop_address is null");
            return this;
        }

        public Criteria andShopAddressIsNotNull() {
            addCriterion("shop_address is not null");
            return this;
        }

        public Criteria andShopAddressEqualTo(String value) {
            addCriterion("shop_address =", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressNotEqualTo(String value) {
            addCriterion("shop_address <>", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressGreaterThan(String value) {
            addCriterion("shop_address >", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressGreaterThanOrEqualTo(String value) {
            addCriterion("shop_address >=", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressLessThan(String value) {
            addCriterion("shop_address <", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressLessThanOrEqualTo(String value) {
            addCriterion("shop_address <=", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressLike(String value) {
            addCriterion("shop_address like", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressNotLike(String value) {
            addCriterion("shop_address not like", value, "shopAddress");
            return this;
        }

        public Criteria andShopAddressIn(List values) {
            addCriterion("shop_address in", values, "shopAddress");
            return this;
        }

        public Criteria andShopAddressNotIn(List values) {
            addCriterion("shop_address not in", values, "shopAddress");
            return this;
        }

        public Criteria andShopAddressBetween(String value1, String value2) {
            addCriterion("shop_address between", value1, value2, "shopAddress");
            return this;
        }

        public Criteria andShopAddressNotBetween(String value1, String value2) {
            addCriterion("shop_address not between", value1, value2, "shopAddress");
            return this;
        }

        public Criteria andShopLogoFileIdIsNull() {
            addCriterion("shop_logo_file_id is null");
            return this;
        }

        public Criteria andShopLogoFileIdIsNotNull() {
            addCriterion("shop_logo_file_id is not null");
            return this;
        }

        public Criteria andShopLogoFileIdEqualTo(Integer value) {
            addCriterion("shop_logo_file_id =", value, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdNotEqualTo(Integer value) {
            addCriterion("shop_logo_file_id <>", value, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdGreaterThan(Integer value) {
            addCriterion("shop_logo_file_id >", value, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_logo_file_id >=", value, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdLessThan(Integer value) {
            addCriterion("shop_logo_file_id <", value, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_logo_file_id <=", value, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdIn(List values) {
            addCriterion("shop_logo_file_id in", values, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdNotIn(List values) {
            addCriterion("shop_logo_file_id not in", values, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_logo_file_id between", value1, value2, "shopLogoFileId");
            return this;
        }

        public Criteria andShopLogoFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_logo_file_id not between", value1, value2, "shopLogoFileId");
            return this;
        }

        public Criteria andShopImgFileIdIsNull() {
            addCriterion("shop_img_file_id is null");
            return this;
        }

        public Criteria andShopImgFileIdIsNotNull() {
            addCriterion("shop_img_file_id is not null");
            return this;
        }

        public Criteria andShopImgFileIdEqualTo(Integer value) {
            addCriterion("shop_img_file_id =", value, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdNotEqualTo(Integer value) {
            addCriterion("shop_img_file_id <>", value, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdGreaterThan(Integer value) {
            addCriterion("shop_img_file_id >", value, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_img_file_id >=", value, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdLessThan(Integer value) {
            addCriterion("shop_img_file_id <", value, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_img_file_id <=", value, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdIn(List values) {
            addCriterion("shop_img_file_id in", values, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdNotIn(List values) {
            addCriterion("shop_img_file_id not in", values, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_img_file_id between", value1, value2, "shopImgFileId");
            return this;
        }

        public Criteria andShopImgFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_img_file_id not between", value1, value2, "shopImgFileId");
            return this;
        }

        public Criteria andShopPhoneNumberIsNull() {
            addCriterion("shop_phone_number is null");
            return this;
        }

        public Criteria andShopPhoneNumberIsNotNull() {
            addCriterion("shop_phone_number is not null");
            return this;
        }

        public Criteria andShopPhoneNumberEqualTo(String value) {
            addCriterion("shop_phone_number =", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberNotEqualTo(String value) {
            addCriterion("shop_phone_number <>", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberGreaterThan(String value) {
            addCriterion("shop_phone_number >", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("shop_phone_number >=", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberLessThan(String value) {
            addCriterion("shop_phone_number <", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("shop_phone_number <=", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberLike(String value) {
            addCriterion("shop_phone_number like", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberNotLike(String value) {
            addCriterion("shop_phone_number not like", value, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberIn(List values) {
            addCriterion("shop_phone_number in", values, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberNotIn(List values) {
            addCriterion("shop_phone_number not in", values, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberBetween(String value1, String value2) {
            addCriterion("shop_phone_number between", value1, value2, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("shop_phone_number not between", value1, value2, "shopPhoneNumber");
            return this;
        }

        public Criteria andShopTelOneIsNull() {
            addCriterion("shop_tel_one is null");
            return this;
        }

        public Criteria andShopTelOneIsNotNull() {
            addCriterion("shop_tel_one is not null");
            return this;
        }

        public Criteria andShopTelOneEqualTo(String value) {
            addCriterion("shop_tel_one =", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneNotEqualTo(String value) {
            addCriterion("shop_tel_one <>", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneGreaterThan(String value) {
            addCriterion("shop_tel_one >", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneGreaterThanOrEqualTo(String value) {
            addCriterion("shop_tel_one >=", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneLessThan(String value) {
            addCriterion("shop_tel_one <", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneLessThanOrEqualTo(String value) {
            addCriterion("shop_tel_one <=", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneLike(String value) {
            addCriterion("shop_tel_one like", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneNotLike(String value) {
            addCriterion("shop_tel_one not like", value, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneIn(List values) {
            addCriterion("shop_tel_one in", values, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneNotIn(List values) {
            addCriterion("shop_tel_one not in", values, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneBetween(String value1, String value2) {
            addCriterion("shop_tel_one between", value1, value2, "shopTelOne");
            return this;
        }

        public Criteria andShopTelOneNotBetween(String value1, String value2) {
            addCriterion("shop_tel_one not between", value1, value2, "shopTelOne");
            return this;
        }

        public Criteria andShopTelTwoIsNull() {
            addCriterion("shop_tel_two is null");
            return this;
        }

        public Criteria andShopTelTwoIsNotNull() {
            addCriterion("shop_tel_two is not null");
            return this;
        }

        public Criteria andShopTelTwoEqualTo(String value) {
            addCriterion("shop_tel_two =", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoNotEqualTo(String value) {
            addCriterion("shop_tel_two <>", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoGreaterThan(String value) {
            addCriterion("shop_tel_two >", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoGreaterThanOrEqualTo(String value) {
            addCriterion("shop_tel_two >=", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoLessThan(String value) {
            addCriterion("shop_tel_two <", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoLessThanOrEqualTo(String value) {
            addCriterion("shop_tel_two <=", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoLike(String value) {
            addCriterion("shop_tel_two like", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoNotLike(String value) {
            addCriterion("shop_tel_two not like", value, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoIn(List values) {
            addCriterion("shop_tel_two in", values, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoNotIn(List values) {
            addCriterion("shop_tel_two not in", values, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoBetween(String value1, String value2) {
            addCriterion("shop_tel_two between", value1, value2, "shopTelTwo");
            return this;
        }

        public Criteria andShopTelTwoNotBetween(String value1, String value2) {
            addCriterion("shop_tel_two not between", value1, value2, "shopTelTwo");
            return this;
        }

        public Criteria andShopEmailIsNull() {
            addCriterion("shop_email is null");
            return this;
        }

        public Criteria andShopEmailIsNotNull() {
            addCriterion("shop_email is not null");
            return this;
        }

        public Criteria andShopEmailEqualTo(String value) {
            addCriterion("shop_email =", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailNotEqualTo(String value) {
            addCriterion("shop_email <>", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailGreaterThan(String value) {
            addCriterion("shop_email >", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailGreaterThanOrEqualTo(String value) {
            addCriterion("shop_email >=", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailLessThan(String value) {
            addCriterion("shop_email <", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailLessThanOrEqualTo(String value) {
            addCriterion("shop_email <=", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailLike(String value) {
            addCriterion("shop_email like", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailNotLike(String value) {
            addCriterion("shop_email not like", value, "shopEmail");
            return this;
        }

        public Criteria andShopEmailIn(List values) {
            addCriterion("shop_email in", values, "shopEmail");
            return this;
        }

        public Criteria andShopEmailNotIn(List values) {
            addCriterion("shop_email not in", values, "shopEmail");
            return this;
        }

        public Criteria andShopEmailBetween(String value1, String value2) {
            addCriterion("shop_email between", value1, value2, "shopEmail");
            return this;
        }

        public Criteria andShopEmailNotBetween(String value1, String value2) {
            addCriterion("shop_email not between", value1, value2, "shopEmail");
            return this;
        }

        public Criteria andShopQqIsNull() {
            addCriterion("shop_qq is null");
            return this;
        }

        public Criteria andShopQqIsNotNull() {
            addCriterion("shop_qq is not null");
            return this;
        }

        public Criteria andShopQqEqualTo(String value) {
            addCriterion("shop_qq =", value, "shopQq");
            return this;
        }

        public Criteria andShopQqNotEqualTo(String value) {
            addCriterion("shop_qq <>", value, "shopQq");
            return this;
        }

        public Criteria andShopQqGreaterThan(String value) {
            addCriterion("shop_qq >", value, "shopQq");
            return this;
        }

        public Criteria andShopQqGreaterThanOrEqualTo(String value) {
            addCriterion("shop_qq >=", value, "shopQq");
            return this;
        }

        public Criteria andShopQqLessThan(String value) {
            addCriterion("shop_qq <", value, "shopQq");
            return this;
        }

        public Criteria andShopQqLessThanOrEqualTo(String value) {
            addCriterion("shop_qq <=", value, "shopQq");
            return this;
        }

        public Criteria andShopQqLike(String value) {
            addCriterion("shop_qq like", value, "shopQq");
            return this;
        }

        public Criteria andShopQqNotLike(String value) {
            addCriterion("shop_qq not like", value, "shopQq");
            return this;
        }

        public Criteria andShopQqIn(List values) {
            addCriterion("shop_qq in", values, "shopQq");
            return this;
        }

        public Criteria andShopQqNotIn(List values) {
            addCriterion("shop_qq not in", values, "shopQq");
            return this;
        }

        public Criteria andShopQqBetween(String value1, String value2) {
            addCriterion("shop_qq between", value1, value2, "shopQq");
            return this;
        }

        public Criteria andShopQqNotBetween(String value1, String value2) {
            addCriterion("shop_qq not between", value1, value2, "shopQq");
            return this;
        }

        public Criteria andShopSortIsNull() {
            addCriterion("shop_sort is null");
            return this;
        }

        public Criteria andShopSortIsNotNull() {
            addCriterion("shop_sort is not null");
            return this;
        }

        public Criteria andShopSortEqualTo(String value) {
            addCriterion("shop_sort =", value, "shopSort");
            return this;
        }

        public Criteria andShopSortNotEqualTo(String value) {
            addCriterion("shop_sort <>", value, "shopSort");
            return this;
        }

        public Criteria andShopSortGreaterThan(String value) {
            addCriterion("shop_sort >", value, "shopSort");
            return this;
        }

        public Criteria andShopSortGreaterThanOrEqualTo(String value) {
            addCriterion("shop_sort >=", value, "shopSort");
            return this;
        }

        public Criteria andShopSortLessThan(String value) {
            addCriterion("shop_sort <", value, "shopSort");
            return this;
        }

        public Criteria andShopSortLessThanOrEqualTo(String value) {
            addCriterion("shop_sort <=", value, "shopSort");
            return this;
        }

        public Criteria andShopSortLike(String value) {
            addCriterion("shop_sort like", value, "shopSort");
            return this;
        }

        public Criteria andShopSortNotLike(String value) {
            addCriterion("shop_sort not like", value, "shopSort");
            return this;
        }

        public Criteria andShopSortIn(List values) {
            addCriterion("shop_sort in", values, "shopSort");
            return this;
        }

        public Criteria andShopSortNotIn(List values) {
            addCriterion("shop_sort not in", values, "shopSort");
            return this;
        }

        public Criteria andShopSortBetween(String value1, String value2) {
            addCriterion("shop_sort between", value1, value2, "shopSort");
            return this;
        }

        public Criteria andShopSortNotBetween(String value1, String value2) {
            addCriterion("shop_sort not between", value1, value2, "shopSort");
            return this;
        }

        public Criteria andShopStatusIsNull() {
            addCriterion("shop_status is null");
            return this;
        }

        public Criteria andShopStatusIsNotNull() {
            addCriterion("shop_status is not null");
            return this;
        }

        public Criteria andShopStatusEqualTo(String value) {
            addCriterion("shop_status =", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusNotEqualTo(String value) {
            addCriterion("shop_status <>", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusGreaterThan(String value) {
            addCriterion("shop_status >", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusGreaterThanOrEqualTo(String value) {
            addCriterion("shop_status >=", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusLessThan(String value) {
            addCriterion("shop_status <", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusLessThanOrEqualTo(String value) {
            addCriterion("shop_status <=", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusLike(String value) {
            addCriterion("shop_status like", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusNotLike(String value) {
            addCriterion("shop_status not like", value, "shopStatus");
            return this;
        }

        public Criteria andShopStatusIn(List values) {
            addCriterion("shop_status in", values, "shopStatus");
            return this;
        }

        public Criteria andShopStatusNotIn(List values) {
            addCriterion("shop_status not in", values, "shopStatus");
            return this;
        }

        public Criteria andShopStatusBetween(String value1, String value2) {
            addCriterion("shop_status between", value1, value2, "shopStatus");
            return this;
        }

        public Criteria andShopStatusNotBetween(String value1, String value2) {
            addCriterion("shop_status not between", value1, value2, "shopStatus");
            return this;
        }

        public Criteria andCreateUserCodeIsNull() {
            addCriterion("create_user_code is null");
            return this;
        }

        public Criteria andCreateUserCodeIsNotNull() {
            addCriterion("create_user_code is not null");
            return this;
        }

        public Criteria andCreateUserCodeEqualTo(String value) {
            addCriterion("create_user_code =", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotEqualTo(String value) {
            addCriterion("create_user_code <>", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeGreaterThan(String value) {
            addCriterion("create_user_code >", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_code >=", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLessThan(String value) {
            addCriterion("create_user_code <", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLessThanOrEqualTo(String value) {
            addCriterion("create_user_code <=", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeLike(String value) {
            addCriterion("create_user_code like", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotLike(String value) {
            addCriterion("create_user_code not like", value, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeIn(List values) {
            addCriterion("create_user_code in", values, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotIn(List values) {
            addCriterion("create_user_code not in", values, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeBetween(String value1, String value2) {
            addCriterion("create_user_code between", value1, value2, "createUserCode");
            return this;
        }

        public Criteria andCreateUserCodeNotBetween(String value1, String value2) {
            addCriterion("create_user_code not between", value1, value2, "createUserCode");
            return this;
        }

        public Criteria andModifyUserCodeIsNull() {
            addCriterion("modify_user_code is null");
            return this;
        }

        public Criteria andModifyUserCodeIsNotNull() {
            addCriterion("modify_user_code is not null");
            return this;
        }

        public Criteria andModifyUserCodeEqualTo(String value) {
            addCriterion("modify_user_code =", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotEqualTo(String value) {
            addCriterion("modify_user_code <>", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeGreaterThan(String value) {
            addCriterion("modify_user_code >", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("modify_user_code >=", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLessThan(String value) {
            addCriterion("modify_user_code <", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLessThanOrEqualTo(String value) {
            addCriterion("modify_user_code <=", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeLike(String value) {
            addCriterion("modify_user_code like", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotLike(String value) {
            addCriterion("modify_user_code not like", value, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeIn(List values) {
            addCriterion("modify_user_code in", values, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotIn(List values) {
            addCriterion("modify_user_code not in", values, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeBetween(String value1, String value2) {
            addCriterion("modify_user_code between", value1, value2, "modifyUserCode");
            return this;
        }

        public Criteria andModifyUserCodeNotBetween(String value1, String value2) {
            addCriterion("modify_user_code not between", value1, value2, "modifyUserCode");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeIn(List values) {
            addCriterion("modify_time in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotIn(List values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return this;
        }
    }
}