package app.cn.qtt.bm.model;

import java.util.Date;

public class TShopInfoDeal {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_info_deal.shop_deal_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer shopDealId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_info_deal.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer shopId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_info_deal.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String createUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_info_deal.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String modifyUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_info_deal.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_info_deal.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date modifyTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_info_deal.shop_deal_id
     *
     * @return the value of t_shop_info_deal.shop_deal_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getShopDealId() {
        return shopDealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_info_deal.shop_deal_id
     *
     * @param shopDealId the value for t_shop_info_deal.shop_deal_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopDealId(Integer shopDealId) {
        this.shopDealId = shopDealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_info_deal.shop_id
     *
     * @return the value of t_shop_info_deal.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_info_deal.shop_id
     *
     * @param shopId the value for t_shop_info_deal.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_info_deal.create_user_code
     *
     * @return the value of t_shop_info_deal.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_info_deal.create_user_code
     *
     * @param createUserCode the value for t_shop_info_deal.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_info_deal.modify_user_code
     *
     * @return the value of t_shop_info_deal.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getModifyUserCode() {
        return modifyUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_info_deal.modify_user_code
     *
     * @param modifyUserCode the value for t_shop_info_deal.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setModifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_info_deal.create_time
     *
     * @return the value of t_shop_info_deal.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_info_deal.create_time
     *
     * @param createTime the value for t_shop_info_deal.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_info_deal.modify_time
     *
     * @return the value of t_shop_info_deal.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_info_deal.modify_time
     *
     * @param modifyTime the value for t_shop_info_deal.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}