package app.cn.qtt.bm.model;

import java.util.Date;

public class TShopDailyInfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.shop_daily_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer shopDailyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.shop_daily_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String shopDailyCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer shopId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.shop_send_content
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String shopSendContent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.shop_daily_email_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String shopDailyEmailStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.shop_daily_sms_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String shopDailySmsStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String createUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String modifyUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_shop_daily_info.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date modifyTime;
    
    /**
     * 用户对象
     * Added by Gabriel Ge 2013-6-24
     */
    private TShopInfo shopInfo;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.shop_daily_id
     *
     * @return the value of t_shop_daily_info.shop_daily_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getShopDailyId() {
        return shopDailyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.shop_daily_id
     *
     * @param shopDailyId the value for t_shop_daily_info.shop_daily_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopDailyId(Integer shopDailyId) {
        this.shopDailyId = shopDailyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.shop_daily_code
     *
     * @return the value of t_shop_daily_info.shop_daily_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getShopDailyCode() {
        return shopDailyCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.shop_daily_code
     *
     * @param shopDailyCode the value for t_shop_daily_info.shop_daily_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopDailyCode(String shopDailyCode) {
        this.shopDailyCode = shopDailyCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.shop_id
     *
     * @return the value of t_shop_daily_info.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.shop_id
     *
     * @param shopId the value for t_shop_daily_info.shop_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.shop_send_content
     *
     * @return the value of t_shop_daily_info.shop_send_content
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getShopSendContent() {
        return shopSendContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.shop_send_content
     *
     * @param shopSendContent the value for t_shop_daily_info.shop_send_content
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopSendContent(String shopSendContent) {
        this.shopSendContent = shopSendContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.shop_daily_email_status
     *
     * @return the value of t_shop_daily_info.shop_daily_email_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getShopDailyEmailStatus() {
        return shopDailyEmailStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.shop_daily_email_status
     *
     * @param shopDailyEmailStatus the value for t_shop_daily_info.shop_daily_email_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopDailyEmailStatus(String shopDailyEmailStatus) {
        this.shopDailyEmailStatus = shopDailyEmailStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.shop_daily_sms_status
     *
     * @return the value of t_shop_daily_info.shop_daily_sms_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getShopDailySmsStatus() {
        return shopDailySmsStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.shop_daily_sms_status
     *
     * @param shopDailySmsStatus the value for t_shop_daily_info.shop_daily_sms_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setShopDailySmsStatus(String shopDailySmsStatus) {
        this.shopDailySmsStatus = shopDailySmsStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.create_user_code
     *
     * @return the value of t_shop_daily_info.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.create_user_code
     *
     * @param createUserCode the value for t_shop_daily_info.create_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.modify_user_code
     *
     * @return the value of t_shop_daily_info.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getModifyUserCode() {
        return modifyUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.modify_user_code
     *
     * @param modifyUserCode the value for t_shop_daily_info.modify_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setModifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.create_time
     *
     * @return the value of t_shop_daily_info.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.create_time
     *
     * @param createTime the value for t_shop_daily_info.create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_shop_daily_info.modify_time
     *
     * @return the value of t_shop_daily_info.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_shop_daily_info.modify_time
     *
     * @param modifyTime the value for t_shop_daily_info.modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	/**
	 * @return the shopInfo
	 */
	public TShopInfo getShopInfo() {
		return shopInfo;
	}

	/**
	 * @param shopInfo the shopInfo to set
	 */
	public void setShopInfo(TShopInfo shopInfo) {
		this.shopInfo = shopInfo;
	}

}