package app.cn.qtt.bm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSysCodeMetadataExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public TSysCodeMetadataExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	protected TSysCodeMetadataExample(TSysCodeMetadataExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_sys_code_metadata
	 * @abatorgenerated  Sat Jun 08 15:02:10 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andCodeMetadataTypeIsNull() {
			addCriterion("code_metadata_type is null");
			return this;
		}

		public Criteria andCodeMetadataTypeIsNotNull() {
			addCriterion("code_metadata_type is not null");
			return this;
		}

		public Criteria andCodeMetadataTypeEqualTo(String value) {
			addCriterion("code_metadata_type =", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeNotEqualTo(String value) {
			addCriterion("code_metadata_type <>", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeGreaterThan(String value) {
			addCriterion("code_metadata_type >", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeGreaterThanOrEqualTo(String value) {
			addCriterion("code_metadata_type >=", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeLessThan(String value) {
			addCriterion("code_metadata_type <", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeLessThanOrEqualTo(String value) {
			addCriterion("code_metadata_type <=", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeLike(String value) {
			addCriterion("code_metadata_type like", value, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeNotLike(String value) {
			addCriterion("code_metadata_type not like", value,
					"codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeIn(List values) {
			addCriterion("code_metadata_type in", values, "codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeNotIn(List values) {
			addCriterion("code_metadata_type not in", values,
					"codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeBetween(String value1, String value2) {
			addCriterion("code_metadata_type between", value1, value2,
					"codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataTypeNotBetween(String value1,
				String value2) {
			addCriterion("code_metadata_type not between", value1, value2,
					"codeMetadataType");
			return this;
		}

		public Criteria andCodeMetadataDescIsNull() {
			addCriterion("code_metadata_desc is null");
			return this;
		}

		public Criteria andCodeMetadataDescIsNotNull() {
			addCriterion("code_metadata_desc is not null");
			return this;
		}

		public Criteria andCodeMetadataDescEqualTo(String value) {
			addCriterion("code_metadata_desc =", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescNotEqualTo(String value) {
			addCriterion("code_metadata_desc <>", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescGreaterThan(String value) {
			addCriterion("code_metadata_desc >", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescGreaterThanOrEqualTo(String value) {
			addCriterion("code_metadata_desc >=", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescLessThan(String value) {
			addCriterion("code_metadata_desc <", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescLessThanOrEqualTo(String value) {
			addCriterion("code_metadata_desc <=", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescLike(String value) {
			addCriterion("code_metadata_desc like", value, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescNotLike(String value) {
			addCriterion("code_metadata_desc not like", value,
					"codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescIn(List values) {
			addCriterion("code_metadata_desc in", values, "codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescNotIn(List values) {
			addCriterion("code_metadata_desc not in", values,
					"codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescBetween(String value1, String value2) {
			addCriterion("code_metadata_desc between", value1, value2,
					"codeMetadataDesc");
			return this;
		}

		public Criteria andCodeMetadataDescNotBetween(String value1,
				String value2) {
			addCriterion("code_metadata_desc not between", value1, value2,
					"codeMetadataDesc");
			return this;
		}
	}
}