package app.cn.qtt.bm.model;

import java.util.Date;

public class TSysLinkUserRole {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.link_user_role_id
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private Integer linkUserRoleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.role_id
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private Integer roleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private String userCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.link_user_role_sort
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private String linkUserRoleSort;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.create_user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private String createUserCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.modify_user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private String modifyUserCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.create_time
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_link_user_role.modify_time
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	private Date modifyTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.link_user_role_id
	 * @return  the value of t_sys_link_user_role.link_user_role_id
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public Integer getLinkUserRoleId() {
		return linkUserRoleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.link_user_role_id
	 * @param linkUserRoleId  the value for t_sys_link_user_role.link_user_role_id
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setLinkUserRoleId(Integer linkUserRoleId) {
		this.linkUserRoleId = linkUserRoleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.role_id
	 * @return  the value of t_sys_link_user_role.role_id
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.role_id
	 * @param roleId  the value for t_sys_link_user_role.role_id
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.user_code
	 * @return  the value of t_sys_link_user_role.user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.user_code
	 * @param userCode  the value for t_sys_link_user_role.user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.link_user_role_sort
	 * @return  the value of t_sys_link_user_role.link_user_role_sort
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public String getLinkUserRoleSort() {
		return linkUserRoleSort;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.link_user_role_sort
	 * @param linkUserRoleSort  the value for t_sys_link_user_role.link_user_role_sort
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setLinkUserRoleSort(String linkUserRoleSort) {
		this.linkUserRoleSort = linkUserRoleSort;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.create_user_code
	 * @return  the value of t_sys_link_user_role.create_user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public String getCreateUserCode() {
		return createUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.create_user_code
	 * @param createUserCode  the value for t_sys_link_user_role.create_user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setCreateUserCode(String createUserCode) {
		this.createUserCode = createUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.modify_user_code
	 * @return  the value of t_sys_link_user_role.modify_user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public String getModifyUserCode() {
		return modifyUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.modify_user_code
	 * @param modifyUserCode  the value for t_sys_link_user_role.modify_user_code
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setModifyUserCode(String modifyUserCode) {
		this.modifyUserCode = modifyUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.create_time
	 * @return  the value of t_sys_link_user_role.create_time
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.create_time
	 * @param createTime  the value for t_sys_link_user_role.create_time
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_link_user_role.modify_time
	 * @return  the value of t_sys_link_user_role.modify_time
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_link_user_role.modify_time
	 * @param modifyTime  the value for t_sys_link_user_role.modify_time
	 * @abatorgenerated  Thu Jun 13 15:31:35 CST 2013
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
}