package app.cn.qtt.bm.model;

import java.util.Date;

public class TSysFile {
    /**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.file_id
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private Integer fileId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.file_path_url
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private String filePathUrl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.file_access_url
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private String fileAccessUrl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.file_status
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private String fileStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.create_user_code
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private String createUserCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.modify_user_code
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private String modifyUserCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.create_time
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_sys_file.modify_time
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	private Date modifyTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.file_id
	 * @return  the value of t_sys_file.file_id
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public Integer getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.file_id
	 * @param fileId  the value for t_sys_file.file_id
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.file_path_url
	 * @return  the value of t_sys_file.file_path_url
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public String getFilePathUrl() {
		return filePathUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.file_path_url
	 * @param filePathUrl  the value for t_sys_file.file_path_url
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setFilePathUrl(String filePathUrl) {
		this.filePathUrl = filePathUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.file_access_url
	 * @return  the value of t_sys_file.file_access_url
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public String getFileAccessUrl() {
		return fileAccessUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.file_access_url
	 * @param fileAccessUrl  the value for t_sys_file.file_access_url
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setFileAccessUrl(String fileAccessUrl) {
		this.fileAccessUrl = fileAccessUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.file_status
	 * @return  the value of t_sys_file.file_status
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public String getFileStatus() {
		return fileStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.file_status
	 * @param fileStatus  the value for t_sys_file.file_status
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setFileStatus(String fileStatus) {
		this.fileStatus = fileStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.create_user_code
	 * @return  the value of t_sys_file.create_user_code
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public String getCreateUserCode() {
		return createUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.create_user_code
	 * @param createUserCode  the value for t_sys_file.create_user_code
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setCreateUserCode(String createUserCode) {
		this.createUserCode = createUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.modify_user_code
	 * @return  the value of t_sys_file.modify_user_code
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public String getModifyUserCode() {
		return modifyUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.modify_user_code
	 * @param modifyUserCode  the value for t_sys_file.modify_user_code
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setModifyUserCode(String modifyUserCode) {
		this.modifyUserCode = modifyUserCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.create_time
	 * @return  the value of t_sys_file.create_time
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.create_time
	 * @param createTime  the value for t_sys_file.create_time
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_sys_file.modify_time
	 * @return  the value of t_sys_file.modify_time
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_sys_file.modify_time
	 * @param modifyTime  the value for t_sys_file.modify_time
	 * @abatorgenerated  Wed Jun 26 10:57:59 CST 2013
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	
}