package app.cn.qtt.bm.model;

import java.util.Date;

public class TSysCaptcha {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer captchaId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String captchaUserCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_user_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String captchaUserMdn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_validation_content
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String captchaValidationContent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date captchaCreateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date captchaModifyTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_begin_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date captchaBeginTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_end_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Date captchaEndTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer captchaStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_fail_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer captchaFailCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private Integer captchaType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_sys_captcha.captcha_buffer_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    private String captchaBufferSn;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_id
     *
     * @return the value of t_sys_captcha.captcha_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getCaptchaId() {
        return captchaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_id
     *
     * @param captchaId the value for t_sys_captcha.captcha_id
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaId(Integer captchaId) {
        this.captchaId = captchaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_user_code
     *
     * @return the value of t_sys_captcha.captcha_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCaptchaUserCode() {
        return captchaUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_user_code
     *
     * @param captchaUserCode the value for t_sys_captcha.captcha_user_code
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaUserCode(String captchaUserCode) {
        this.captchaUserCode = captchaUserCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_user_mdn
     *
     * @return the value of t_sys_captcha.captcha_user_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCaptchaUserMdn() {
        return captchaUserMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_user_mdn
     *
     * @param captchaUserMdn the value for t_sys_captcha.captcha_user_mdn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaUserMdn(String captchaUserMdn) {
        this.captchaUserMdn = captchaUserMdn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_validation_content
     *
     * @return the value of t_sys_captcha.captcha_validation_content
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCaptchaValidationContent() {
        return captchaValidationContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_validation_content
     *
     * @param captchaValidationContent the value for t_sys_captcha.captcha_validation_content
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaValidationContent(String captchaValidationContent) {
        this.captchaValidationContent = captchaValidationContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_create_time
     *
     * @return the value of t_sys_captcha.captcha_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCaptchaCreateTime() {
        return captchaCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_create_time
     *
     * @param captchaCreateTime the value for t_sys_captcha.captcha_create_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaCreateTime(Date captchaCreateTime) {
        this.captchaCreateTime = captchaCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_modify_time
     *
     * @return the value of t_sys_captcha.captcha_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCaptchaModifyTime() {
        return captchaModifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_modify_time
     *
     * @param captchaModifyTime the value for t_sys_captcha.captcha_modify_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaModifyTime(Date captchaModifyTime) {
        this.captchaModifyTime = captchaModifyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_begin_time
     *
     * @return the value of t_sys_captcha.captcha_begin_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCaptchaBeginTime() {
        return captchaBeginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_begin_time
     *
     * @param captchaBeginTime the value for t_sys_captcha.captcha_begin_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaBeginTime(Date captchaBeginTime) {
        this.captchaBeginTime = captchaBeginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_end_time
     *
     * @return the value of t_sys_captcha.captcha_end_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Date getCaptchaEndTime() {
        return captchaEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_end_time
     *
     * @param captchaEndTime the value for t_sys_captcha.captcha_end_time
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaEndTime(Date captchaEndTime) {
        this.captchaEndTime = captchaEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_status
     *
     * @return the value of t_sys_captcha.captcha_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getCaptchaStatus() {
        return captchaStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_status
     *
     * @param captchaStatus the value for t_sys_captcha.captcha_status
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaStatus(Integer captchaStatus) {
        this.captchaStatus = captchaStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_fail_count
     *
     * @return the value of t_sys_captcha.captcha_fail_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getCaptchaFailCount() {
        return captchaFailCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_fail_count
     *
     * @param captchaFailCount the value for t_sys_captcha.captcha_fail_count
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaFailCount(Integer captchaFailCount) {
        this.captchaFailCount = captchaFailCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_type
     *
     * @return the value of t_sys_captcha.captcha_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public Integer getCaptchaType() {
        return captchaType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_type
     *
     * @param captchaType the value for t_sys_captcha.captcha_type
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaType(Integer captchaType) {
        this.captchaType = captchaType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_sys_captcha.captcha_buffer_sn
     *
     * @return the value of t_sys_captcha.captcha_buffer_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public String getCaptchaBufferSn() {
        return captchaBufferSn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_sys_captcha.captcha_buffer_sn
     *
     * @param captchaBufferSn the value for t_sys_captcha.captcha_buffer_sn
     *
     * @abatorgenerated Sat Jun 08 15:02:10 CST 2013
     */
    public void setCaptchaBufferSn(String captchaBufferSn) {
        this.captchaBufferSn = captchaBufferSn;
    }
}